import {useRef,useState} from 'react';
import {ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronDown, Cloud, Crown, FileCheck2, Headphones, LockKeyhole, Phone, ShieldCheck, Sparkles, X} from 'lucide-react';
import {LanguagePicker,UiText} from './Language';
import './awaaz.css';

const transcript=[
 {speaker:'Awaaz',text:'नमस्ते! मैं आवाज़, KaamSet का AI calling teammate हूँ। यह एक fictional shop order का छोटा test call है। क्या अभी एक मिनट बात कर सकते हैं?'},
 {speaker:'Customer',text:'हाँ हाँ करिए।'},
 {speaker:'Awaaz',text:'शर्मा डेली मार्ट से आपका demo order DEMO-101 है। इसमें 2 किलो आटा है जिसकी कीमत 120 रुपये और 1 लीटर कुकिंग ऑयल है जिसकी कीमत 160 रुपये, कुल 280 रुपये हैं। ये सब पिकअप के लिए हैं, डिलीवरी नहीं। क्या ये items सही हैं?'},
 {speaker:'Customer',text:'हाँ जी।'},
 {speaker:'Awaaz',text:'आपके लिए पिकअप का preferred time क्या रहेगा? ये एक preference है, appointment confirm नहीं।'},
 {speaker:'Customer',text:'आज शाम का कर दीजिए।'},
 {speaker:'Customer',text:'आज शाम का।'},
 {speaker:'Customer',text:'का 7 बजेगा।'},
 {speaker:'Awaaz',text:'आपका preferred pickup time आज शाम 7 बजे है, मैं इसे owner को दिखाऊंगा। और कुछ मदद चाहिए?'},
 {speaker:'Customer',text:'नीचे।'},
 {speaker:'Awaaz',text:'ठीक है,'},
 {speaker:'Customer',text:'नहीं ठीक है, बाकी तो सब बढ़िया ही है।'},
 {speaker:'Awaaz',text:'बहुत धन्यवाद! आपका test पूरा हुआ। Sharma Daily Mart को धन्यवाद कहें। शुभ दिन!'},
];

function AwaazCharacter(){return <div className="awaaz-avatar" role="img" aria-label="Awaaz, a pixel calling teammate wearing a headset"><div className="awaaz-pixel"><div className="awaaz-hair"/><div className="awaaz-face"/><div className="awaaz-eyes"/><div className="awaaz-shirt"/><div className="awaaz-headset"/></div></div>;}

export default function Awaaz(){
 const gate=useRef<HTMLDialogElement>(null),[view,setView]=useState<'result'|'transcript'>('result');
 function premium(){gate.current?.showModal();}
 return <div className="awaaz-page">
  <header className="awaaz-header"><a className="awaaz-brand" href="/"><img src="/kaamset-mark.svg" alt=""/><span>Kaam<span>Set</span></span></a><a href="/" className="awaaz-back"><ArrowLeft size={15}/><UiText text="Back to my team"/></a><LanguagePicker/></header>
  <main className="awaaz-main">
   <div className="awaaz-breadcrumb"><UiText text="AI teammates"/><span>/</span><span>Awaaz</span><span className="awaaz-badge"><Crown size={12}/><UiText text="Premium"/></span></div>
   <section className="awaaz-hero">
    <div className="awaaz-hero-copy"><span className="awaaz-eyebrow"><Headphones size={15}/><UiText text="A CALLING TEAMMATE FOR YOUR BUSINESS"/></span><h1><UiText text="A familiar voice."/><br/><span><UiText text="A useful next step."/></span></h1><p><UiText text="Meet Awaaz. Your AI teammate that talks to customers in Hindi/Hinglish, confirms the details and brings the conversation back to you."/></p><div className="awaaz-actions"><button onClick={premium} className="awaaz-primary"><Crown size={16}/><UiText text="Unlock premium calling"/><ArrowRight size={16}/></button><a href="#awaaz-test" className="awaaz-secondary"><UiText text="See the real test"/><ChevronDown size={16}/></a></div><div className="awaaz-hero-note"><ShieldCheck size={14}/><UiText text="Verified live pilot · Merchant activation preview"/></div></div>
    <div className="awaaz-stage"><div className="awaaz-stage-grid"/><div className="awaaz-stage-top"><span className="awaaz-signal"><i/><UiText text="REAL CALL COMPLETED"/></span><span>59 <UiText text="seconds"/></span></div><AwaazCharacter/><div className="awaaz-stage-name">Awaaz</div><p><UiText text="Hindi / Hinglish · Bolna + Sarvam"/></p><div className="awaaz-sound" aria-hidden="true">{Array.from({length:21},(_,i)=><i key={i} style={{height:`${8+(i%5)*5}px`,animationDelay:`${i*.07}s`}}/>)}</div><span className="awaaz-stage-caption"><UiText text="Character animation is decorative; the test below is real."/></span><div className="awaaz-float"><CheckCircle2 size={20}/><div><strong><UiText text="Pickup preference captured"/></strong><span><UiText text="7 pm · For owner review"/></span></div></div></div>
   </section>
   <div className="awaaz-proof-strip"><div><CheckCircle2/><strong><UiText text="Real outbound call"/></strong><small><UiText text="Completed through Bolna"/></small></div><div><Headphones/><strong><UiText text="Hindi / Hinglish"/></strong><small><UiText text="Sarvam speech configured"/></small></div><div><Cloud/><strong><UiText text="Runs on cloud servers"/></strong><small><UiText text="The merchant browser is not the caller"/></small></div><div><ShieldCheck/><strong><UiText text="Approval first"/></strong><small><UiText text="Specific recipient, brief and call limit"/></small></div></div>
   <section className="awaaz-test" id="awaaz-test"><div className="awaaz-section-head"><div><span className="awaaz-eyebrow"><UiText text="THE PROOF, IN A REAL CONVERSATION"/></span><h2><UiText text="One order. One call. A clear outcome."/></h2><p><UiText text="Actual pilot call on 3 October 2026. This was a fictional order with a consenting tester."/></p></div><span className="awaaz-completed"><CheckCircle2 size={15}/><UiText text="Completed"/> · 59s</span></div>
    <div className="awaaz-test-grid"><aside className="awaaz-order"><span className="awaaz-eyebrow">DEMO-101</span><h3>Sharma Daily Mart</h3><p><UiText text="Approved fictional order"/></p><div><span><UiText text="2 kg atta"/></span><strong>₹120</strong></div><div><span><UiText text="1 litre cooking oil"/></span><strong>₹160</strong></div><div className="awaaz-order-total"><span><UiText text="Order total"/></span><strong>₹280</strong></div><span className="awaaz-order-note"><FileCheck2 size={16}/><UiText text="Pickup only. No payment due for this test."/></span></aside>
    <div className="awaaz-conversation"><div className="awaaz-view-tabs" role="group" aria-label="Test evidence view"><button aria-pressed={view==='result'} onClick={()=>setView('result')}><UiText text="What Awaaz achieved"/></button><button aria-pressed={view==='transcript'} onClick={()=>setView('transcript')}><UiText text="Actual transcript"/></button></div>{view==='result'?<div className="awaaz-outcomes"><div><span>01</span><section><h3><UiText text="Introduced itself and asked permission"/></h3><p><UiText text="Awaaz identified itself as an AI teammate and explained that this was a test."/></p></section><Check size={19}/></div><div><span>02</span><section><h3><UiText text="Confirmed the exact order"/></h3><p><UiText text="Two approved items. Correct ₹280 total. No invented discount or delivery promise."/></p></section><Check size={19}/></div><div><span>03</span><section><h3><UiText text="Captured the customer’s preference"/></h3><p><UiText text="The tester requested pickup that evening at 7 pm. Awaaz repeated it for owner review, without confirming an appointment."/></p></section><Check size={19}/></div><button className="awaaz-text-button" onClick={()=>setView('transcript')}><UiText text="Read the actual conversation"/><ArrowRight size={15}/></button></div>:<div className="awaaz-transcript" aria-label="Actual Hindi call transcript">{transcript.map((turn,i)=><div key={i} className={turn.speaker==='Awaaz'?'awaaz-turn-agent':'awaaz-turn-customer'}><strong>{turn.speaker==='Awaaz'?'Awaaz':<UiText text="Tester"/>}</strong><p lang="hi">{turn.text}</p></div>)}</div>}<div className="awaaz-evidence-note"><ShieldCheck size={15}/><UiText text="Verified pilot evidence. No real order was placed, appointment confirmed or payment collected."/></div></div></div>
   </section>
   <section className="awaaz-premium-plan"><div><span className="awaaz-badge"><Crown size={12}/><UiText text="PAID ADD-ON"/></span><h2><UiText text="Add a voice to your AI team."/></h2><p><UiText text="Awaaz is a premium integration. Merchant calling will require activation, a connected Bolna account and available provider credits."/></p><div className="awaaz-plan-tags"><span><Phone size={14}/><UiText text="Approved calls"/></span><span><Cloud size={14}/><UiText text="Cloud execution"/></span><span><FileCheck2 size={14}/><UiText text="Call evidence"/></span></div></div><div className="awaaz-plan-cta"><strong><UiText text="Premium calling"/></strong><p><UiText text="Paid activation · Provider usage extra"/></p><button className="awaaz-primary" onClick={premium}><LockKeyhole size={15}/><UiText text="View activation requirements"/></button><small><UiText text="UI preview. Billing is not enabled yet."/></small></div></section>
   <section className="awaaz-activation"><h2><UiText text="A simple setup, after premium activation."/></h2><div><article><span>01</span><h3><UiText text="Connect Bolna"/></h3><p><UiText text="Enter your key through a secure connection flow. Trial accounts require verified recipient numbers."/></p></article><article><span>02</span><h3><UiText text="Approve the job"/></h3><p><UiText text="Choose the customer, language, approved facts and the maximum call duration."/></p></article><article><span>03</span><h3><UiText text="Review what happened"/></h3><p><UiText text="Read the actual transcript and customer requests. Uncertain outcomes wait for verification."/></p></article></div><small><UiText text="Automated scheduling, merchant billing and operational write-back still need production integration. This page presents the verified voice pilot."/></small></section>
  </main><footer className="awaaz-footer"><span>KaamSet · Awaaz</span><span><UiText text="Useful conversations. Clear evidence. Owner control."/></span><a href="https://www.bolna.ai/docs" target="_blank" rel="noreferrer">Bolna <UiText text="documentation"/> ↗</a></footer>
  <dialog ref={gate} className="awaaz-gate" onClick={e=>{if(e.target===e.currentTarget)gate.current?.close();}}><button className="awaaz-gate-close" aria-label="Close premium details" onClick={()=>gate.current?.close()}><X size={20}/></button><span className="awaaz-badge"><Crown size={12}/><UiText text="PREMIUM CALLING"/></span><div className="awaaz-gate-icon"><Sparkles size={26}/></div><h2><UiText text="Awaaz is a paid add-on."/></h2><p><UiText text="The voice integration has passed a real Hindi/Hinglish test. Purchase and merchant activation are not enabled in this preview, and no payment will be taken."/></p><ul><li><Check size={15}/><UiText text="Merchant-owned Bolna connection"/></li><li><Check size={15}/><UiText text="Available provider credits and eligible numbers"/></li><li><Check size={15}/><UiText text="Approved recipient, business facts and call budget"/></li></ul><button className="awaaz-primary" onClick={()=>{gate.current?.close();setView('transcript');document.getElementById('awaaz-test')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}}><UiText text="View the completed live test"/><ArrowRight size={16}/></button><small><UiText text="UI-level premium gate · Billing not active"/></small></dialog>
 </div>;
}
