import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ExternalLink,Mail,Users,X} from 'lucide-react';
import type {LeadDeskState} from './api';
import {UiText,useLanguage} from './Language';
type Item={leadId:string;recipientEmail:string;subject:string;body:string};
export default function BulkLeadOutreach({data,canSend,busy,onSetup,onConnections,onApprove,onReviewHeld}:{data:LeadDeskState;canSend:boolean;busy:boolean;onSetup:()=>void;onConnections:()=>void;onReviewHeld:(id:string)=>void;onApprove:(input:{requestKey:string;items:Item[];approved:true;businessContactConfirmed:true})=>Promise<boolean>}){
 const {t}=useLanguage(),[selection,setSelection]=useState<string[]>([]),[items,setItems]=useState<Item[]|null>(null),[approved,setApproved]=useState(false),[error,setError]=useState(''),key=useRef(crypto.randomUUID()),dialog=useRef<HTMLElement>(null);
 const eligible=data.records.filter(l=>!l.suppressed&&l.fit!=='not_a_fit'&&l.emails.length&&!data.outreach.some(o=>o.leadId===l.id||l.emails.includes(o.recipientEmail)));
 const chosen=eligible.filter(l=>selection.includes(l.id)),duplicate=items&&new Set(items.map(i=>i.recipientEmail)).size!==items.length;
 useEffect(()=>{if(!items)return;const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.focus();const handle=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)setItems(null);if(e.key==='Tab'){const focusable=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')||[]),first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handle);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',handle);previous?.focus()}},[!!items,busy]);
 function edit(index:number,change:Partial<Item>){setItems(old=>old!.map((i,n)=>n===index?{...i,...change}:i));setApproved(false);setError('');key.current=crypto.randomUUID()}
 const batches=data.batches||[];
 return <section className="lead-bulk-panel" aria-labelledby="bulk-outreach-title"><div className="lead-bulk-heading"><Users size={20}/><div><h3 id="bulk-outreach-title"><UiText text="Personal outreach, as a batch"/></h3><p><UiText text="Choose up to 10 sourced business contacts. Review each email, then approve the exact batch. Nothing is selected automatically."/></p></div></div>
  {eligible.length?<><div className="lead-bulk-selection">{eligible.map(l=><label className="office-check" key={l.id}><input type="checkbox" checked={selection.includes(l.id)} disabled={busy||!selection.includes(l.id)&&chosen.length>=10} onChange={e=>setSelection(ids=>e.target.checked?[...ids,l.id]:ids.filter(id=>id!==l.id))}/><span><strong>{l.sourceTitle}</strong><small>{l.emails[0]}</small></span></label>)}</div><div className="lead-bulk-footer"><span>{chosen.length}/10 <UiText text="selected"/></span><button className="office-primary" disabled={busy||!chosen.length} onClick={()=>{setItems(chosen.map(l=>({leadId:l.id,recipientEmail:l.emails[0],subject:l.subject,body:l.body})));setApproved(false);key.current=crypto.randomUUID()}}><Mail size={16}/><UiText text="Preview selected emails"/><ArrowRight size={15}/></button></div></>:<p className="lead-bulk-empty"><UiText text="Find and review public business contacts first. Contacts already approached or marked do not contact are excluded."/></p>}
  {batches.slice().reverse().slice(0,5).map(batch=>{const rows=data.outreach.filter(o=>batch.outreachIds.includes(o.id)),sent=rows.filter(o=>o.state==='sent').length,held=rows.filter(o=>['waiting_owner','uncertain'].includes(o.state)).length;return <div className="lead-batch-result" key={batch.id}><strong><UiText text="Approved batch"/> · {rows.length} <UiText text="emails"/></strong><span>{sent} <UiText text="Gmail confirmed"/> · {rows.length-sent-held} <UiText text="in progress"/> · {held} <UiText text="need review"/></span><details><summary><UiText text="See each delivery result"/></summary>{rows.map(o=><p key={o.id}><strong>{o.recipientEmail}</strong> · <UiText text={o.state==='sent'?'Sent':o.state==='sending'?'Sending':o.state==='queued'?'Queued':o.state==='uncertain'?'Uncertain':'Owner review'}/>{o.reason&&<small>{o.reason}</small>}{o.receipt&&<small>{o.receipt.logRef} · {o.receipt.providerMessageId}</small>}{o.resumable&&<button className="office-text" disabled={busy} onClick={()=>onReviewHeld(o.leadId)}><UiText text="Review held email"/><ArrowRight size={14}/></button>}</p>)}</details></div>})}
  {items&&<div className="office-modal-overlay"><section className="office-modal lead-bulk-review" ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="lead-bulk-review-title"><button className="office-close" aria-label={t('Close batch review')} disabled={busy} onClick={()=>setItems(null)}><X size={20}/></button><span className="office-eyebrow"><UiText text="Lakshya · Exact batch approval"/></span><h2 id="lead-bulk-review-title"><UiText text="Review every recipient and message"/></h2><p><UiText text="Emails are delivered at least 10 seconds apart. Failed or uncertain sends are held for review; they are never automatically resent."/></p>
   {items.map((item,index)=>{const lead=data.records.find(l=>l.id===item.leadId)!;return <fieldset className="lead-bulk-email" key={item.leadId} disabled={busy}><legend>{index+1}. {lead.sourceTitle}</legend><a href={lead.sourceUrl} target="_blank" rel="noopener noreferrer" className="office-text"><UiText text="Review public source"/><ExternalLink size={14}/></a><label><UiText text="Business email"/><select value={item.recipientEmail} onChange={e=>edit(index,{recipientEmail:e.target.value})}>{lead.emails.map(email=><option key={email}>{email}</option>)}</select></label><label><UiText text="Subject"/><input value={item.subject} maxLength={160} onChange={e=>edit(index,{subject:e.target.value})}/></label><label><UiText text="Exact message"/><textarea rows={5} value={item.body} maxLength={3000} onChange={e=>edit(index,{body:e.target.value})}/></label></fieldset>})}
   {duplicate&&<p className="office-error" role="alert"><UiText text="An email address is selected more than once. Choose one unique contact per message."/></p>}{error&&<p className="office-error" role="alert">{error}</p>}
   {!canSend?<div className="lead-setup-actions"><p><UiText text="Connect Gmail and enable Lakshya’s approved outreach job before sending this batch."/></p><button className="office-text" onClick={()=>{setItems(null);onConnections()}}><UiText text="Connect Gmail"/></button><button className="office-text" onClick={()=>{setItems(null);onSetup()}}><UiText text="Review Lakshya’s settings"/></button></div>:<><label className="office-check"><input type="checkbox" checked={approved} disabled={busy} onChange={e=>setApproved(e.target.checked)}/><span><UiText text="I reviewed every public business contact and approve the exact recipients, subjects and messages shown above. Each message is relevant to that business."/></span></label><button className="office-primary" disabled={busy||!approved||!!duplicate||items.some(i=>i.subject.trim().length<3||i.body.trim().length<10)} onClick={()=>void(async()=>{setError('');if(await onApprove({requestKey:key.current,items,approved:true,businessContactConfirmed:true})){setItems(null);setSelection([]);setApproved(false)}else setError(t('Batch approval was not confirmed. Close this review to see the exact setup issue, refresh saved results and keep this same approval before retrying.'))})()}><Mail size={16}/>{busy?t('Saving exact batch…'):`${t('Approve')} ${items.length} ${t('emails')}`}</button></>}
  </section></div>}
 </section>
}
