import {useRef,useState} from 'react';
import {ArrowRight,Brain,Check,Download,FileText,Link2,LoaderCircle,ShieldCheck,Sparkles,Trash2,Upload,Users} from 'lucide-react';
import {api,type RecordPreview,type WorkspaceState} from './api';
import {readyTeams,type ReadyTeamId} from './ReadyTeams';
import PixelTeammate from './PixelTeammate';
import './business-start.css';
const money=(n:number)=>`₹${(n/100).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
export default function BusinessStart({token,workspace,onChange,onChoose,onOpenTask}:{token:string;workspace:WorkspaceState;onChange:()=>Promise<unknown>;onChoose:(id:ReadyTeamId)=>void;onOpenTask:(id:string)=>void}){
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[preview,setPreview]=useState<RecordPreview|null>(null),[file,setFile]=useState<{name:string;csv:string}|null>(null),[approved,setApproved]=useState(false),[practice,setPractice]=useState(false),[node,setNode]=useState('brain');
 const input=useRef<HTMLInputElement>(null),locked=useRef(false),attempt=useRef<{key:string;kind:string}|null>(null),guide=workspace.businessGuide;
 const [answers,setAnswers]=useState<Record<string,string>>({}),[answersApproved,setAnswersApproved]=useState(false);
 async function act(label:string,fn:()=>Promise<void>){if(locked.current)return;locked.current=true;setBusy(label);setError('');setNotice('');try{await fn();await onChange()}catch(e){setError((e as Error).message)}finally{setBusy('');locked.current=false}}
 async function download(){await act('Preparing your sample file',async()=>{const csv=await api.recordSample(),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='kaamset-practice-sales.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Sample downloaded. Upload that CSV below to review the eight fictional records.');});}
 async function upload(f:File){setApproved(false);setPreview(null);setFile(null);if(f.size>60000){setError('Choose a CSV under 60 KB with up to 200 records.');return}await act('Reading and checking your records',async()=>{const csv=await f.text(),result=await api.previewRecords(token,csv);setFile({name:f.name,csv});setPreview(result);setPractice(result.kind==='practice');});}
 async function save(){if(!preview||!file||!approved)return;await act('Saving reviewed record memory',async()=>{const r=await api.saveRecords(token,{csv:file.csv,fileName:file.name,previewHash:preview.hash,practice,approved:true});setPreview(null);setFile(null);setApproved(false);setNotice(r.reused?'This file was already saved. It was not counted twice.':r.kind==='practice'?'Practice records saved separately. Ask Sia to show what they mean.':'Reported records saved to private business memory. They are not provider-verified payments.');});}
 async function saveAnswers(){if(!guide||!answersApproved)return;await act('Saving your approved answers',async()=>{const extra=guide.questions.filter(q=>answers[q]?.trim()).map(q=>`${q}\n${answers[q].trim()}`).join('\n\n');if(!extra)return;await api.saveBrief(token,workspace.brief+'\n\n[Owner-approved setup answers]\n'+extra,true);setAnswers({});setAnswersApproved(false);setNotice('Your answers are saved for every teammate. Review and reactivate existing teams after this facts change, then ask Sia for an updated guide.');});}
 async function demonstrate(kind:'practice'|'owner_import'){await act('Starting Sia’s record review in the cloud',async()=>{
   const old=workspace.blueprints.find(b=>b.presetId==='sia');const team=await api.readyTeam(token,'sia',{},old?.revision);
   if(team.state!=='active')await api.teammateControl(token,team,'activate');
   const signature=kind+':'+(workspace.recordImports||[]).filter(i=>i.kind===kind).map(i=>i.hash).join(':');if(attempt.current?.kind!==signature)attempt.current={key:crypto.randomUUID(),kind:signature};
   await api.runTeammate(token,team.id,kind==='practice'?'Show a simple demonstration using ONLY the fictional practice record files in importedRecordMemory. Explain the reported received, pending and refunded amounts, payment methods and three useful next actions. State that these are fictional practice records, not actual business or verified Paytm transactions. Do not combine them with business records or claim profit.':'Review ONLY owner-imported reported business record files in importedRecordMemory. Explain received, pending and refunded amounts and one useful next action in my language. State file dates and coverage, and that imported records are not payment-provider verification. Do not combine practice records or claim profit.',attempt.current.key);
   onOpenTask(team.id);
 });}
 const imports=workspace.recordImports||[],summary=workspace.recordSummary;
 const nodes=[{id:'facts',label:'Your business',detail:workspace.briefApproved?'Facts approved':'Needs review',Icon:FileText},{id:'records',label:'Your records',detail:`${imports.reduce((n,x)=>n+x.rowCount,0)} imported entries`,Icon:FileText},{id:'rules',label:'Your boundaries',detail:'You stay in charge',Icon:ShieldCheck},{id:'brain',label:'Shared business memory',detail:workspace.briefApproved?'Ready for your team':'Approve facts first',Icon:Brain},{id:'teams',label:'Your teammates',detail:`${workspace.blueprints.filter(b=>b.state==='active').length} active teams`,Icon:Users},{id:'apps',label:'Your connections',detail:`${workspace.connections.filter(c=>c.status==='connected').length+(workspace.whatsappLinked?1:0)} connected apps`,Icon:Link2}];
 return <div className="business-start">{error&&<p className="office-error" role="alert">{error}</p>}{notice&&<p className="office-notice" role="status">{notice}</p>}{busy&&<p className="business-start-progress" role="status"><LoaderCircle size={18} className="spin"/>{busy}</p>}
 <section className="office-card business-guide"><div className="business-guide-head"><div><span className="office-eyebrow">TELL US ONCE. START SMALL.</span><h2>Your business, in your words.</h2><p>No technical setup to learn. Sia uses your description to suggest useful help and ask only the missing essentials.</p></div><PixelTeammate id="chotu" name="Sia" state={busy.includes('Sia')?'working':'idle'}/></div>
 {guide?<><p className="business-guide-summary">{guide.summary}</p><div className="business-recommendations">{guide.recommendedTeams.map(r=>{const t=readyTeams.find(x=>x.code===r.id);return t&&<button key={r.id} disabled={!!busy} onClick={()=>onChoose(t.code)}><PixelTeammate id={t.id} name={t.name.split(' · ')[0]}/><span><strong>{t.name}</strong><small>{r.reason}</small></span><ArrowRight size={16}/></button>})}</div>{!!guide.questions.length&&<div className="business-guide-questions"><h3>A few details will make your team more useful</h3><div className="business-question-fields">{guide.questions.map(q=><label key={q}>{q}<input value={answers[q]||''} maxLength={500} disabled={!!busy} placeholder="A short answer is enough. Skip what you don’t know yet." onChange={e=>{setAnswers({...answers,[q]:e.target.value});setAnswersApproved(false)}}/></label>)}</div><label className="office-check"><input type="checkbox" checked={answersApproved} disabled={!!busy} onChange={e=>setAnswersApproved(e.target.checked)}/><span>I approve these answers as facts my team can use.</span></label><button className="office-secondary" disabled={!!busy||!answersApproved||!guide.questions.some(q=>answers[q]?.trim())||workspace.brief.length+guide.questions.reduce((n,q)=>n+q.length+(answers[q]?.length||0),60)>12000} onClick={()=>void saveAnswers()}>Save my answers <Check size={15}/></button><p>You can skip unknown details. Your team asks you before acting on missing facts.</p></div>}<details><summary>What Sia used</summary>{guide.sourceQuotes.map((q,i)=><blockquote key={i}>{q}</blockquote>)}</details></>:<button className="office-primary" disabled={!!busy||!workspace.briefApproved} onClick={()=>void act('Sia is understanding your business',async()=>{await api.understandBusiness(token)})}><Sparkles size={16}/>Help me choose the right teammates</button>}
 <small className="business-guide-footnote">Recommendations prepare your setup. Live replies, posting and payments still need your account connection and approval.</small></section>
 <section className="office-card record-memory"><span className="office-eyebrow">SEE YOUR TEAM WORK WITH RECORDS</span><h2>Start with a file you can understand.</h2><p>Download a small sales-and-payments example, upload it, review the entries, then let Sia explain them. You can also use your own CSV in the same format.</p><div className="office-actions"><button className="office-secondary" disabled={!!busy} onClick={()=>void download()}><Download size={16}/>Download sample CSV</button><button className="office-primary" disabled={!!busy} onClick={()=>input.current?.click()}><Upload size={16}/>Upload records</button><input ref={input} type="file" accept=".csv,text/csv" hidden onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void upload(f)}}/></div><p className="record-example-note">The example is fictional tea-stall transaction history. It resembles a merchant report; it is not a Paytm account statement or a real payment.</p>
 {preview&&file&&<div className="record-preview"><div className="record-preview-heading"><h3>Review {file.name}</h3><span>{preview.rows.length} records · {preview.alreadyImported?'Already saved':preview.kind==='practice'?'Fictional sample':'Reported history'}</span></div><div className="record-table-wrap"><table><caption>First {Math.min(5,preview.rows.length)} rows of your checked file</caption><thead><tr><th>Date</th><th>Description</th><th>Amount</th><th>Method</th><th>Status</th></tr></thead><tbody>{preview.rows.slice(0,5).map(r=><tr key={r.id}><td>{r.date}</td><td>{r.description}</td><td>{money(r.amountPaise)}</td><td>{r.method}</td><td>{r.status}</td></tr>)}</tbody></table></div><label className="office-check"><input type="checkbox" checked={practice} disabled={preview.kind==='practice'} onChange={e=>{setPractice(e.target.checked);setApproved(false)}}/><span>Keep this file as fictional practice data, separate from business records.</span></label><label className="office-check"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/><span>I reviewed these entries and approve using them in private team memory. Uploading does not verify any payment.</span></label><button className="office-primary" disabled={!!busy||!approved} onClick={()=>void save()}><Check size={16}/>Save reviewed records</button></div>}
 {!!imports.length&&<><div className="record-file-list">{imports.map(f=><article key={f.id}><FileText size={18}/><div><strong>{f.fileName}</strong><small>{f.rowCount} records · {f.kind==='practice'?'Fictional practice':'Owner-reported history'}</small></div><button className="office-icon-button" aria-label={`Remove ${f.fileName}`} disabled={!!busy} onClick={()=>void act('Removing this record source',async()=>{await api.removeRecords(token,f.id)})}><Trash2 size={16}/></button></article>)}</div>{(['practice','owner_import'] as const).map(kind=>{const s=kind==='practice'?summary?.practice:summary?.reportedBusiness;return !!s?.records&&<div className="record-review-action" key={kind}><div><strong>{kind==='practice'?'Fictional practice':'Reported business history'}</strong><p>{s.records} entries · {money(s.receivedPaise)} reported received · {money(s.pendingPaise)} pending · {money(s.refundedPaise)} refunded</p></div><button className="office-primary" disabled={!!busy||!workspace.briefApproved||workspace.controls?.paused||workspace.controls?.humanTakeover} onClick={()=>void demonstrate(kind)}><Sparkles size={16}/>{kind==='practice'?'Show Sia on sample records':'Ask Sia about my records'}</button></div>})}</>}
 <small className="record-example-note">Record imports support explanations. They never change your bills, stock, khata or verified Paytm collections. Keep passwords, OTPs and payment keys out of files.</small></section>
 <section className="office-card business-memory-map"><span className="office-eyebrow">ONE MEMORY. A CONNECTED TEAM.</span><h2>See what your team knows.</h2><p>Choose a card to inspect its source. The lines show how your approved information reaches the team.</p><div className="memory-network" role="group" aria-label="Business memory connections"><svg viewBox="0 0 1000 420" preserveAspectRatio="none" aria-hidden="true"><path d="M165 85 C165 195 500 110 500 210 M500 85 L500 210 M835 85 C835 195 500 110 500 210 M500 210 C500 290 280 260 280 350 M500 210 C500 290 720 260 720 350"/></svg>{nodes.map(n=><button key={n.id} className={`memory-node memory-node-${n.id} ${node===n.id?'selected':''}`} aria-pressed={node===n.id} onClick={()=>setNode(n.id)}><n.Icon size={20}/><strong>{n.label}</strong><small>{n.detail}</small></button>)}</div><div className="memory-node-detail" aria-live="polite"><h3>{nodes.find(n=>n.id===node)?.label}</h3>{node==='facts'?<p>{workspace.brief}</p>:node==='records'?<p>{imports.length?imports.map(f=>`${f.fileName}: ${f.rowCount} ${f.kind==='practice'?'fictional':'reported'} entries`).join(' · '):'No imported records yet. Your team can still use your approved business description.'}</p>:node==='rules'?<p>{workspace.business?.rules||'Ask the owner about missing facts, discounts and uncertain commercial decisions. Approve external actions separately.'}</p>:node==='teams'?<p>{workspace.blueprints.map(b=>`${b.teamIdentity?.lead||b.plan.name}: ${b.state}`).join(' · ')||'Choose your first ready teammate.'}</p>:node==='apps'?<p>{workspace.connections.map(c=>`${c.toolkit}: ${c.status}`).concat(workspace.whatsappLinked?['WhatsApp: paired']:[]).join(' · ')||'No account is connected. Internal advice and drafts are still available.'}</p>:<><p>Your approved description and recorded sources are shared inside this workspace. Customer replies use approved public business facts; private record history stays with owner-facing work.</p><p>{workspace.providers?.cognee?workspace.brain?.cogneeState==='not_indexed'?'Source search needs the latest sources saved below. Your team can already use the saved local facts and records.':'Source search is processing. Search below to inspect the exact passages available.':'Your team can use your approved facts and saved records. Advanced source search is not enabled.'}</p></>}</div><small>Your team uses these saved sources. Connected apps check their permissions before performing an action.</small></section>
 </div>;
}
