import {useEffect,useRef,useState} from 'react';
import {Trash2,Upload} from 'lucide-react';
import {api,type BusinessAssetInput} from './api';
import {useLanguage} from './Language';
export function AssetPicker({assets,onChange,onError,onBusyChange}:{assets:BusinessAssetInput[];onChange:(assets:BusinessAssetInput[])=>void;onError:(error:string)=>void;onBusyChange?:(busy:boolean)=>void}){
  const {t}=useLanguage(),input=useRef<HTMLInputElement>(null),[busy,setBusy]=useState(false),sequence=useRef(0),mounted=useRef(true);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;sequence.current++}},[]);
  useEffect(()=>{onBusyChange?.(busy);return()=>onBusyChange?.(false)},[busy,onBusyChange]);
  async function read(files:FileList|null){if(!files)return;const mine=++sequence.current;const items=[...files];if(items.length+assets.length>3){onError('Choose up to 3 business images.');return}if(items.some(f=>!['image/jpeg','image/png'].includes(f.type)||f.size>1500000)){onError('Choose JPEG or PNG images under 1.5 MB each.');return}setBusy(true);try{const added=await Promise.all(items.map(async f=>{const photo=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('This image could not be read. Choose it again.'));reader.readAsDataURL(f)});const img=new Image();img.src=`data:${f.type};base64,${photo}`;await img.decode();if(img.width>4096||img.height>4096)throw new Error('Use images smaller than 4096 × 4096.');return {photo,alt:f.name.replace(/\.[^.]+$/,'').slice(0,200),kind:'photo' as const,rightsConfirmed:true as const};}));if(mounted.current&&mine===sequence.current){onError('');onChange([...assets,...added])}}catch(e){if(mounted.current)onError((e as Error).message)}finally{if(mounted.current&&mine===sequence.current)setBusy(false)}}
  return <section className="business-assets"><h3>{t('Your logo & business photos')}</h3><p>{t('Optional. Add your logo, shop or product photos now. Your teams can reuse them after your approval.')}</p><input ref={input} type="file" accept="image/jpeg,image/png" multiple hidden onChange={e=>{void read(e.target.files);e.target.value=''}}/><button type="button" className="office-secondary" disabled={busy||assets.length>=3} onClick={()=>input.current?.click()}><Upload size={16}/>{t(busy?'Reading images…':'Add business images')}</button><small>{t('Up to 3 JPEG/PNG images, 1.5 MB each. Keep personal documents and payment QR codes out of this gallery.')}</small><div className="business-asset-grid">{assets.map((a,i)=><article key={i}><img src={`data:image/jpeg;base64,${a.photo}`} alt={a.alt}/><label>{t('Image description')}<input maxLength={200} minLength={2} value={a.alt} onChange={e=>onChange(assets.map((a,n)=>n===i?{...a,alt:e.target.value}:a))}/></label><label>{t('Image type')}<select value={a.kind} onChange={e=>onChange(assets.map((a,n)=>n===i?{...a,kind:e.target.value as 'logo'|'photo'}:a))}><option value="photo">{t('Business photo')}</option><option value="logo">{t('Logo')}</option></select></label><button type="button" className="office-text" onClick={()=>onChange(assets.filter((_,n)=>n!==i))}><Trash2 size={14}/>{t('Remove image')}</button></article>)}</div></section>;
}
export function BusinessPhotoLibrary({token,onSelect,onError}:{token:string|null;onSelect:(photo:string)=>void;onError:(error:string)=>void}){const {t}=useLanguage(),[images,setImages]=useState<{id:string;alt:string;src:string}[]|null>(null),[busy,setBusy]=useState(false);return <div className="business-photo-library"><button type="button" className="office-text" disabled={!token||busy} onClick={async()=>{if(!token)return;setBusy(true);try{setImages((await api.businessAssets(token)).assets)}catch(e){onError((e as Error).message)}finally{setBusy(false)}}}>{t('Choose from my business images')}</button>{images&&<div className="business-asset-grid">{images.map(image=><button type="button" className="office-secondary" key={image.id} onClick={()=>{onSelect(image.src.split(',')[1]);setImages(null)}}><img src={image.src} alt={image.alt}/><span>{image.alt}</span></button>)}{!images.length&&<p>{t('Add your logo or photos in Business & memory.')}</p>}</div>}</div>}
export function SavedBusinessAssets({token,onChange}:{token:string;onChange:()=>Promise<unknown>}){const {t}=useLanguage(),[assets,setAssets]=useState<BusinessAssetInput[]>([]),[ready,setReady]=useState(false),[approved,setApproved]=useState(false),[reading,setReading]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{let active=true;api.businessAssets(token).then(r=>{if(active){setAssets(r.assets.map(a=>({alt:a.alt,kind:a.kind,photo:a.src.split(',')[1],rightsConfirmed:true})));setReady(true)}}).catch(e=>{if(active)setError((e as Error).message)});return()=>{active=false}},[token]);return <section className="office-card">{!ready?<p>{t('Loading your business images…')}</p>:<><AssetPicker assets={assets} onChange={a=>{setAssets(a);setApproved(false)}} onError={setError} onBusyChange={setReading}/><label className="office-check"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/><span>{t('I own or have permission to use these images. They stay private until I approve publishing.')}</span></label><button className="office-primary" disabled={busy||reading||!approved||assets.some(a=>a.alt.trim().length<2)} onClick={async()=>{setBusy(true);setError('');try{await api.saveBusinessAssets(token,assets);setApproved(false);await onChange()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{t(busy?'Saving…':'Save business images')}</button></>}{error&&<p className="office-error" role="alert">{error}</p>}</section>}
