import {useEffect,useState} from 'react';
import {ArrowRight,CalendarDays,Check,ShieldCheck} from 'lucide-react';
import {api,type Order,type Slot} from './api';
const when=(v:string)=>new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'}).format(new Date(v));
const money=(n:number|null)=>n===null?'Awaiting merchant confirmation':`₹${(n/100).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
export default function CustomerOrder({cap}:{cap:string}){const [order,setOrder]=useState<Order|null>(null),[slots,setSlots]=useState<Slot[]>([]),[selected,setSelected]=useState(''),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{api.customerOrder(cap).then(setOrder).catch(e=>setError(e.message))},[cap]);
  useEffect(()=>{if(!order||!['accepted','processing'].includes(order.state))return;const timer=setInterval(()=>api.customerOrder(cap).then(setOrder).catch(e=>setError(e.message)),2500);return()=>clearInterval(timer)},[cap,order?.state]);
  async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <main className="customer-quote-page"><a className="quote-brand" href="/">kaam<span>set</span></a><section className="merchant-tool"><span className="card-kicker">PRIVATE CUSTOMER QUOTE · TRIAL</span><h1>{order?.name||'Your merchant’s quote'}</h1>{error&&<p className="workspace-error" role="alert">{error}</p>}{!order&&!error&&<p role="status">Opening your quote…</p>}{order&&<><div className="quote-total"><strong>{money(order.amountPaise)}</strong><span>{order.quantity} × {money(order.unitPricePaise)} + fee {money(order.deliveryPaise)}</span></div><p>{order.terms}</p><span className="readiness-pill">{order.state.replaceAll('_',' ')}</span>{order.reason&&<p>{order.reason}</p>}
  {order.state==='quoted'&&<>{order.kind==='appointment'&&<div className="quote-slots"><h2><CalendarDays size={20}/> Pick a live appointment</h2><p>India time (IST). Availability is checked again when the booking is made.</p><button className="button button-dark" disabled={busy} onClick={()=>run(async()=>{const r=await api.orderSlots(cap);setSlots(r.slots);setSelected('');if(!r.slots.length)setError('No slots available in the approved hours. Please contact the merchant.')})}>{busy?'Checking…':'Find available times'}</button>{slots.map(s=><label className="slot-option" key={s.id}><input type="radio" name="slot" checked={selected===s.id} onChange={()=>setSelected(s.id)}/>{when(s.start)}</label>)}</div>}
  <label className="approval-checkbox"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/> I accept this exact quote and the listed terms.</label><button className="button button-primary" disabled={busy||!accepted||order.kind==='appointment'&&!selected||Date.parse(order.expiresAt)<=Date.now()} onClick={()=>run(async()=>setOrder(await api.acceptOrder(cap,selected||undefined)))}>Accept {order.kind==='appointment'?'and request booking':'quote'} <ArrowRight size={17}/></button><p className="small-muted">Quote valid until {when(order.expiresAt)}. Work continues in the cloud after acceptance.</p></>}
  {['accepted','processing'].includes(order.state)&&<p role="status">Your acceptance is saved. The cloud worker is handling the request.</p>}{order.state==='confirmed'&&<div className="setup-box"><Check size={20}/><strong>{order.kind==='appointment'&&order.calendarVerified?'Appointment verified in the merchant’s calendar':'Order accepted'}</strong>{order.selectedSlot&&<p>{when(order.selectedSlot.start)}</p>}<p>Payment: {order.paymentState?.replaceAll('_',' ')||'Not requested'}. Delivery or fulfilment is tracked separately.</p>{order.paymentUrl&&<a className="button button-primary" href={order.paymentUrl}>Open Paytm test payment <ArrowRight size={16}/></a>}</div>}
  <div className="quote-safety"><ShieldCheck size={18}/><p>This link only opens this quote. Paytm is in staging mode. The trial does not fulfil a real order.</p></div></>}</section></main>;
}
