import {useEffect,useState} from 'react';
import {QRCodeSVG} from 'qrcode.react';
import {Check,MessageCircle,Pause,ShieldCheck} from 'lucide-react';
import {api,type WhatsAppState,type WorkspaceState} from './api';

export default function InboxPanel({token,workspace,onChange}:{token:string|null;workspace:WorkspaceState|null;onChange:()=>Promise<unknown>}){
 const [wa,setWa]=useState<WhatsAppState|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[consent,setConsent]=useState<Record<string,boolean>>({}),[drafts,setDrafts]=useState<Record<string,string>>({});
 async function act(label:string,fn:()=>Promise<unknown>){if(busy)return;setBusy(label);setError('');try{await fn();await onChange()}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 useEffect(()=>{if(!token)return;let live=true;const read=()=>api.whatsapp(token).then(s=>{if(live)setWa(s)}).catch(()=>{});read();const timer=setInterval(read,5000);return()=>{live=false;clearInterval(timer)}},[token]);
 const channels=[{id:'instagram_dm',name:'Instagram DMs',detail:'New eligible inbound DMs only. Meta messaging permissions and its reply window apply.',toolkit:'instagram'},{id:'instagram_comments',name:'Instagram comments',detail:'Routine comments on posts prepared and published through this workspace.',toolkit:'instagram'},{id:'gmail',name:'Gmail sales desk',detail:'New inbox enquiries after activation. Replies stay in the original customer thread.',toolkit:'gmail'}];
 const rule=(id:string)=><label className="approval-checkbox"><input type="checkbox" checked={!!consent[id]} onChange={e=>setConsent({...consent,[id]:e.target.checked})}/><span>I approve routine replies from my business brief. Stock, discounts, complaints and unverified bookings require my review.</span></label>;
 return <section className="inbox-panel"><span className="card-kicker">YOUR CLOUD CUSTOMER DESK</span><h2>One conversation. One speaking teammate.</h2><p>Connect an account, approve routine reply rules and activate a teammate with the matching channel skill. Your browser can close while the cloud team works.</p>
 {error&&<div className="workspace-error" role="alert">{error}</div>}
 <div className="inbox-setup">{channels.map(c=>{const enabled=workspace?.channels?.[c.id]?.enabled,connected=workspace?.connections.some(x=>x.toolkit===c.toolkit&&x.status==='connected');return <article key={c.id}><MessageCircle size={20}/><h3>{c.name}</h3><p>{c.detail}</p>{workspace?.channels?.[c.id]?.error&&<p className="channel-error">{workspace.channels[c.id].error}</p>}{enabled?<button className="button button-dark" disabled={!!busy||!token} onClick={()=>act('Pausing replies',()=>api.channel(token!,c.id,false))}><Pause size={15}/>Pause channel</button>:<>{rule(c.id)}<button className="button button-dark" disabled={!!busy||!token||!connected||!consent[c.id]} onClick={()=>act('Checking account access',()=>api.channel(token!,c.id,true))}><Check size={15}/>Check access & enable</button>{!connected&&<small>Connect and verify {c.toolkit==='gmail'?'Gmail':'Instagram'} in Connections first.</small>}</>}</article>})}</div>
 <section className="whatsapp-pairing"><div><span className="card-kicker">WHATSAPP WEB / LINKED DEVICE PILOT</span><h3>Pair your own WhatsApp</h3><p>The cloud keeps the paired session. Scan using WhatsApp → Settings → Linked devices. This uses an unofficial linked-device adapter, with a maximum of two guest devices on this demo server.</p><p>Status: <strong>{wa?.state||'Not connected'}</strong>{wa?.phone&&` · ${wa.phone}`}</p>{wa?.error&&<p>{wa.error}</p>}{wa?.canLink&&<button className="button button-dark" disabled={!!busy||!token} onClick={()=>act('Preparing WhatsApp pairing',async()=>{await api.whatsappAction(token!,'link');setWa(await api.whatsapp(token!))})}>Show pairing QR</button>}{wa?.canReconnect&&<button className="button button-dark" disabled={!!busy||!token} onClick={()=>act('Reconnecting WhatsApp',async()=>{await api.whatsappAction(token!,'reconnect');setWa(await api.whatsapp(token!))})}>Reconnect</button>}{wa?.linked&&<><button className="text-button" disabled={!!busy||!token} onClick={()=>act('Unlinking your device',async()=>{await api.whatsappAction(token!,'unlink');setWa(await api.whatsapp(token!))})}>Unlink this device</button>{wa.salesAutoReplyEnabled?<button className="text-button" disabled={!!busy} onClick={()=>act('Pausing WhatsApp replies',async()=>{await api.whatsappAction(token!,'disable');setWa(await api.whatsapp(token!))})}>Pause routine replies</button>:<>{rule('whatsapp')}<button className="button button-primary" disabled={!!busy||wa.state!=='connected'||!consent.whatsapp} onClick={()=>act('Enabling approved WhatsApp rules',async()=>{await api.whatsappAction(token!,'enable');setWa(await api.whatsapp(token!))})}>Enable routine replies</button></>}</>}</div>{wa?.qr&&<div className="pairing-qr"><QRCodeSVG value={wa.qr} size={220} marginSize={4}/><p>Only scan this for your own account.</p></div>}</section>
 <div className="setup-box"><ShieldCheck size={17}/><strong>Owner handoff stays visible</strong><p>Use Pause teammate or owner takeover to stop automatic replies. Unknown delivery remains uncertain. KaamSet does not resend it automatically.</p></div>
 <div className="inbox-results"><h3>Enquiries and handoffs</h3>{!workspace?.inbox?.length?<p>New messages after activation will appear here. No historical inbox is imported into this guest view.</p>:workspace.inbox.slice().reverse().map(i=><article key={i.id}><div className="task-result-head"><span className="readiness-pill">{i.channel.replaceAll('_',' ')} · {i.state.replaceAll('_',' ')}</span><small>{new Date(i.createdAt).toLocaleString('en-IN')}</small></div><h4>Customer enquiry</h4><p className="result-prose">{i.text}</p>{i.reply&&<><h4>Teammate response</h4><p className="result-prose">{i.reply}</p></>}{i.reason&&<p>{i.reason}</p>}{i.state==='human_review'&&<div><label>Exact owner-approved reply<textarea rows={4} maxLength={2000} value={drafts[i.id]??i.reply??''} onChange={e=>setDrafts({...drafts,[i.id]:e.target.value})}/></label><button className="button button-dark" disabled={!!busy||!token||!(drafts[i.id]??i.reply??'').trim()} onClick={()=>act('Queuing your exact approved reply',()=>api.approveInboxReply(token!,i.id,drafts[i.id]??i.reply??''))}>Approve this reply and send</button><p className="small-muted">Review every fact. Release owner takeover before approved cloud sending.</p></div>}{i.providerReplyId&&<details><summary>Delivery evidence</summary><code>{i.providerReplyId}<br/>{i.logRef}</code></details>}</article>)}</div>
 </section>;
}
