import {useEffect,useState} from 'react';
import {ArrowRight,Brain,CalendarDays,Check,Clock3,Copy,Package,Send} from 'lucide-react';
import {QRCodeSVG} from 'qrcode.react';
import {api,type Offer,type WorkspaceState} from './api';
import PixelTeammate from './PixelTeammate';

const money=(n:number|null)=>n===null?'Needs confirmation':`₹${(n/100).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const when=(s:string)=>new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'}).format(new Date(s));
const starter:Offer={id:'snack-case',name:'Snack assortment case',kind:'product',unitPricePaise:120000,minimumQuantity:2,availableQuantity:null,reorderAt:2,deliveryPaise:null,durationMinutes:60,terms:'Fictional trial offer. Stock and delivery must be approved by the owner. No discount or delivery guarantee.'};
function useAction(onChange:()=>Promise<unknown>){const [busy,setBusy]=useState(false),[error,setError]=useState('');
  async function run(fn:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');try{await fn();await onChange()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return {busy,error,run};
}
export function SharedBrain({workspace}:{workspace:WorkspaceState|null}){const b=workspace?.brain,m=b?.snapshot;return <section className="merchant-tool brain-panel"><div className="card-head"><div><span className="card-kicker">ONE CONNECTED BUSINESS BRAIN</span><h2>Your whole team remembers the same business.</h2></div><Brain size={28}/></div><p>Each LLM teammate uses your approved playbook and the latest workspace records. Customer replies receive business facts; private owner records stay in your workspace.</p>
  <div className="brain-flow"><span>Approved facts</span><ArrowRight size={16}/><span>Shared memory</span><ArrowRight size={16}/><span>LLM reasoning</span><ArrowRight size={16}/><span>Approved work + evidence</span></div>
  <div className="merchant-metrics"><div><strong>{m?.acceptedOrders??0}</strong><span>Accepted orders</span></div><div><strong>{m?.awaitingOwner??0}</strong><span>Need your attention</span></div><div><strong>{money(m?.verifiedCollectionPaise??0)}</strong><span>Verified collections</span></div><div><strong>{m?.reminders.scheduled??0}</strong><span>Scheduled reminders</span></div></div>
  <div className="setup-box"><strong>Cognee memory</strong><p>{workspace?.providers?.cognee?b?.cogneeState==='not_indexed'?'Save the approved playbook to Cognee in Business brief. All teammates can retrieve its verified sources.':'Your approved playbook is shared through Cognee. Changed facts need indexing again.':'The shared playbook is available now. Add the Cognee server settings to enable source retrieval across teammates.'}</p></div>
  {!!m?.offers.length&&<div className="stock-cards">{m.offers.map(o=><div key={o.id}><Package size={16}/><strong>{o.name}</strong><span>{o.quantity===null?'Add stock':`${o.quantity} recorded units`}</span><small>{o.reorderSuggested?'Reorder review needed':`Reorder threshold: ${o.reorderAt}`}</small></div>)}</div>}
  <p className="small-muted">Stock is owner-recorded. Your LLM teammates explain priorities and missing facts; delivery and accounting are separate.</p></section>}

export function Catalogue({token,workspace,ensureToken,onChange}:{token:string|null;workspace:WorkspaceState|null;ensureToken:()=>Promise<string>;onChange:()=>Promise<unknown>}){
  const [offers,setOffers]=useState<Offer[]>(workspace?.commerce?.offers||[starter]),[approved,setApproved]=useState(false);const {busy,error,run}=useAction(onChange);
  useEffect(()=>{if(workspace?.commerce?.offers)setOffers(workspace.commerce.offers)},[workspace?.commerce?.offers.map(o=>`${o.id}:${o.availableQuantity}`).join('|')]);
  function edit(i:number,key:keyof Offer,value:unknown){setApproved(false);setOffers(old=>old.map((o,n)=>n===i?{...o,[key]:value}:o))}
  return <section className="merchant-tool"><div className="card-head"><div><span className="card-kicker">PRODUCTS, SERVICES & STOCK</span><h2>Give your team facts it can work with.</h2></div><Package size={25}/></div><p>Add up to six trial offers. An empty stock or delivery field asks for your confirmation before a quote can be accepted.</p>{error&&<p className="workspace-error" role="alert">{error}</p>}
    {offers.map((o,i)=><fieldset className="offer-editor" key={i}><legend>Offer {i+1}</legend><div className="merchant-form-grid"><label>Name<input value={o.name} onChange={e=>edit(i,'name',e.target.value)} maxLength={100}/></label><label>Type<select value={o.kind} onChange={e=>{edit(i,'kind',e.target.value);if(e.target.value==='appointment')edit(i,'minimumQuantity',1)}}><option value="product">Product</option><option value="appointment">Appointment</option></select></label><label>Price per unit (₹)<input type="number" min={1} max={100000} step="0.01" value={o.unitPricePaise/100} onChange={e=>edit(i,'unitPricePaise',Math.round(Number(e.target.value)*100))}/></label><label>Minimum quantity<input type="number" min={1} max={100} value={o.minimumQuantity} onChange={e=>edit(i,'minimumQuantity',Number(e.target.value))}/></label>
    {o.kind==='product'?<><label>Recorded stock<input type="number" min={0} max={1000} placeholder="Unknown" value={o.availableQuantity??''} onChange={e=>edit(i,'availableQuantity',e.target.value===''?null:Number(e.target.value))}/></label><label>Reorder at<input type="number" min={0} max={1000} value={o.reorderAt??2} onChange={e=>edit(i,'reorderAt',Number(e.target.value))}/></label></>:<label>Appointment length (minutes)<input type="number" min={15} max={180} value={o.durationMinutes} onChange={e=>edit(i,'durationMinutes',Number(e.target.value))}/></label>}
    <label>Delivery / booking fee (₹)<input type="number" min={0} max={10000} step="0.01" placeholder="Unknown" value={o.deliveryPaise===null?'':o.deliveryPaise/100} onChange={e=>edit(i,'deliveryPaise',e.target.value===''?null:Math.round(Number(e.target.value)*100))}/></label></div><label>Terms<textarea rows={2} value={o.terms} maxLength={500} onChange={e=>edit(i,'terms',e.target.value)}/></label>{offers.length>1&&<button className="text-button" onClick={()=>{setOffers(offers.filter((_,n)=>n!==i));setApproved(false)}}>Remove offer</button>}</fieldset>)}
    <div className="builder-actions"><button className="text-button" disabled={offers.length>=6} onClick={()=>{setOffers([...offers,{...starter,id:`offer-${crypto.randomUUID().slice(0,8)}`,name:'New offer'}]);setApproved(false)}}>Add another offer +</button></div><label className="approval-checkbox"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/> I approve these prices, recorded stock and terms.</label><button className="button button-dark" disabled={busy||!approved} onClick={()=>run(async()=>{await api.commerceSetup(await ensureToken(),offers);setApproved(false)})}>{busy?'Saving…':'Save approved offers'} <Check size={16}/></button>
    <div className="setup-box"><CalendarDays size={20}/><strong>Appointments in your calendar</strong><p>Trial booking hours: Monday–Saturday, 10am–7pm IST, at least one hour ahead. Connect Google Calendar, then approve your writable primary calendar.</p><button className="button button-dark" disabled={busy||!token||!workspace?.commerce||!workspace.connections.some(c=>c.toolkit==='googlecalendar'&&c.status==='connected')} onClick={()=>run(()=>api.approveCalendar(token!))}>{workspace?.commerce?.calendar?'Recheck primary calendar':'Approve my primary calendar'}</button>{workspace?.commerce?.calendar&&<p>Approved: {workspace.commerce.calendar.label}</p>}</div>
  </section>;
}

export function MilanScheduler({token,workspace,onChange,onBuild,onPair}:{token:string|null;workspace:WorkspaceState|null;onChange:()=>Promise<unknown>;onBuild:()=>void;onPair:()=>void}){
  const {busy,error,run}=useAction(onChange);const [contacts,setContacts]=useState<{id:string;name:string}[]>([]),[contact,setContact]=useState(''),[message,setMessage]=useState('Namaste! Aap payment karne ke baad reference share kar denge? Agar koi help chahiye toh batayein. Dhanyavaad.'),[consent,setConsent]=useState(false),[order,setOrder]=useState('');
  const [at,setAt]=useState(()=>new Date(Date.now()+19800000+300000).toISOString().slice(0,16));const milan=workspace?.blueprints.find(b=>b.state==='active'&&b.plan.skills.includes('whatsapp_schedule'));
  const [draftId,setDraftId]=useState('');const draft=workspace?.tasks.find(t=>t.id===draftId);
  useEffect(()=>{if(draft?.state==='completed'&&draft.result&&draft.result.output.length<=1500){setMessage(draft.result.output);setConsent(false);setDraftId('')}},[draft?.state,draft?.result]);
  return <section className="merchant-tool milan-panel"><div className="milan-heading"><PixelTeammate id="milan" state={busy?'working':'idle'}/><div><span className="card-kicker">MEET MILAN · YOUR PERSONAL PA</span><h2>“Yeh kaam yaad se kar dena.”</h2><p>Approve a person, a personal message and a time. Milan takes care of the reminder from the cloud.</p></div></div>{error&&<p className="workspace-error" role="alert">{error}</p>}
    {!milan&&<div className="setup-box"><strong>Give Milan a scheduled-reminder job first.</strong><p>Review the playbook, pair WhatsApp and activate the checked teammate.</p><button className="button button-dark" onClick={onBuild}>Build Milan <ArrowRight size={16}/></button></div>}
    <div className="builder-actions"><button className="text-button" onClick={onPair}>Pair WhatsApp</button><button className="text-button" disabled={!token||busy} onClick={()=>run(async()=>{await api.whatsapp(token!);const r=await api.reminderContacts(token!);setContacts(r.contacts);setContact(r.contacts[0]?.id||'')})}>Load my recent contacts</button></div><p className="small-muted">Existing individual chats only. Ask the contact to message the paired number if their chat is missing. No groups or bulk outreach.</p>
    <div className="merchant-form-grid"><label>Person<select value={contact} onChange={e=>{setContact(e.target.value);setConsent(false)}}><option value="">Choose a contact</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Send at (India time)<input type="datetime-local" value={at} onChange={e=>setAt(e.target.value)}/></label></div><label>Exact message<textarea rows={4} maxLength={1500} value={message} onChange={e=>{setMessage(e.target.value);setConsent(false)}}/></label><label>Stop after a verified payment (optional)<select value={order} onChange={e=>setOrder(e.target.value)}><option value="">General personal reminder</option>{workspace?.commerce?.orders.filter(o=>o.customerAcceptedAt).map(o=><option value={o.id} key={o.id}>{o.name} · {money(o.amountPaise)}</option>)}</select></label>
    <button className="text-button" disabled={busy||!token||!milan||!contact||!!draftId&&['queued','working'].includes(draft?.state||'queued')} onClick={()=>run(async()=>{const r=await api.runTeammate(token!,milan!.id,`Draft exactly one personal WhatsApp reminder for ${contacts.find(c=>c.id===contact)?.name||'the selected contact'} in the owner's language. The output field must contain only the send-ready message, under 700 characters. Follow the approved playbook. Ask for missing facts; do not invent payment amounts or prior commitments. Intended message: ${message}`);setDraftId(r.id)})}>{draftId&&['queued','working'].includes(draft?.state||'queued')?'Milan is drafting in the cloud…':'Ask Milan to personalise this draft'}</button>{draft?.state==='failed'&&<p>Milan could not complete this draft. Review Work & results before trying again.</p>}
    <label className="approval-checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> This contact expects this message. I approve the exact recipient, text and time.</label><button className="button button-primary" disabled={busy||!token||!milan||!contact||!consent||message.trim().length<3||!at} onClick={()=>run(async()=>{await api.scheduleReminder(token!,{blueprintId:milan!.id,contactId:contact,message,at:new Date(`${at}:00+05:30`).toISOString(),consentConfirmed:true,...(order?{orderId:order}:{})});setConsent(false)})}>Schedule with Milan <Send size={16}/></button><p className="small-muted">Your browser can close. Quiet hours 10pm–7am IST delay sends. Guest jobs last within the 24-hour workspace. Keep the cloud session paired.</p>
    <div className="reminder-list">{workspace?.reminders?.slice().reverse().map(r=><article key={r.id}><div><Clock3 size={16}/><strong>{r.contactName}</strong><span className="readiness-pill">{r.state.replaceAll('_',' ')}</span></div><p>{r.message}</p><small>{when(r.at)}</small>{r.reason&&<p>{r.reason}</p>}{r.providerMessageId&&<p className="small-muted">WhatsApp receipt: {r.providerMessageId}</p>}{['scheduled','waiting_owner'].includes(r.state)&&<button className="text-button" disabled={busy||!token} onClick={()=>run(()=>api.cancelReminder(token!,r.id))}>Cancel message</button>}</article>)}</div>
  </section>;
}

export function OrderDesk({token,workspace,onChange}:{token:string|null;workspace:WorkspaceState|null;onChange:()=>Promise<unknown>}){
  const {busy,error,run}=useAction(onChange);const offers=workspace?.commerce?.offers||[];const [offer,setOffer]=useState(''),[quantity,setQuantity]=useState(1),[url,setUrl]=useState(''),[fee,setFee]=useState<Record<string,string>>({}),[copied,setCopied]=useState(false);
  useEffect(()=>{if(offers.length&&!offers.some(o=>o.id===offer)){setOffer(offers[0].id);setQuantity(offers[0].minimumQuantity)}},[offers.map(o=>o.id).join('|'),offer]);
  return <section className="merchant-tool"><div className="card-head"><div><span className="card-kicker">MA’S ORDER DESK</span><h2>A clear quote. An explicit yes.</h2></div><PixelTeammate id="ma"/></div><p>Create an exact quote from approved offers. Your customer opens a private link, accepts the amount, and picks a live calendar slot for an appointment.</p>{error&&<p className="workspace-error" role="alert">{error}</p>}
    {!offers.length?<div className="setup-box">Save approved products or services in Business brief to start.</div>:<><div className="merchant-form-grid"><label>Offer<select value={offer} onChange={e=>{setOffer(e.target.value);setQuantity(offers.find(o=>o.id===e.target.value)?.minimumQuantity||1)}}>{offers.map(o=><option value={o.id} key={o.id}>{o.name} · {money(o.unitPricePaise)}</option>)}</select></label><label>Quantity<input type="number" min={offers.find(o=>o.id===offer)?.minimumQuantity||1} max={1000} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label></div><button className="button button-dark" disabled={busy||!token||!offer} onClick={()=>run(async()=>{const q=await api.quote(token!,offer,quantity);setUrl(q.state==='quoted'?q.url:'');setCopied(false)})}>Prepare exact quote <ArrowRight size={16}/></button></>}
    {url&&<div className="quote-share"><QRCodeSVG value={url} size={140} marginSize={3}/><div><strong>Customer quote link</strong><p>Share this link with the intended customer. It gives access to this quote only.</p><a href={url} target="_blank" rel="noreferrer">Open customer quote</a><button className="text-button" onClick={()=>run(async()=>{await navigator.clipboard.writeText(url);setCopied(true)})}><Copy size={15}/>{copied?'Copied':'Copy link'}</button></div></div>}
    <div className="order-list">{workspace?.commerce?.orders.slice().reverse().map(o=><article key={o.id}><div className="task-result-head"><strong>{o.name} × {o.quantity}</strong><span className="readiness-pill">{o.state.replaceAll('_',' ')}</span></div><p>{money(o.amountPaise)} · {o.paymentState?.replaceAll('_',' ')||'Payment not requested'}</p>{o.reason&&<p>{o.reason}</p>}{!!o.calendarReceipt&&<p className="small-muted">Calendar provider receipt saved.</p>}{o.state==='awaiting_owner'&&<div><label>Approved delivery / booking fee (₹)<input type="number" min={0} max={10000} step="0.01" value={fee[o.id]??''} onChange={e=>setFee({...fee,[o.id]:e.target.value})}/></label><button className="button button-dark" disabled={busy||!token||fee[o.id]===undefined||fee[o.id]===''} onClick={()=>run(async()=>{const q=await api.approveQuote(token!,o.id,Math.round(Number(fee[o.id])*100));setUrl(q.url)})}>Confirm stock and this fee</button></div>}{(['uncertain','confirmed'].includes(o.state)&&(o.kind==='appointment'||!!o.paymentState&&!['setup_needed'].includes(o.paymentState)))&&<button className="text-button" disabled={busy||!token} onClick={()=>run(()=>api.verifyOrder(token!,o.id))}>Verify provider result</button>}{o.state==='confirmed'&&workspace?.providers?.paytm&&!o.paymentUrl&&<button className="text-button" disabled={busy||!token} onClick={()=>run(()=>api.orderPayment(token!,o.id))}>Create Paytm test payment request</button>}{o.paymentUrl&&<a href={o.paymentUrl} target="_blank" rel="noreferrer">Open Paytm staging payment</a>}</article>)}</div><p className="small-muted">Payment requests need Paytm staging setup. An accepted order or verified payment does not mark delivery complete.</p>
  </section>;
}
