import {useLanguage} from './Language';
import {UiText} from './Language';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Brain,CalendarDays,Check,Clock3,Copy,Package,Send} from 'lucide-react';
import {QRCodeSVG} from 'qrcode.react';
import {api,type Offer,type CommerceHours,type WorkspaceState} from './api';
import PixelTeammate from './PixelTeammate';

const money=(n:number|null)=>n===null?'Needs confirmation':`₹${(n/100).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const when=(s:string)=>new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'}).format(new Date(s));
const starter:Offer={id:'first-offer',name:'',kind:'product',unitPricePaise:0,minimumQuantity:1,availableQuantity:null,reorderAt:2,deliveryPaise:null,durationMinutes:60,terms:'Stock, delivery and commercial exceptions need owner approval.'};
function useAction(onChange:()=>Promise<unknown>){const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const inFlight=useRef(false);
  async function run(fn:()=>Promise<unknown>){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{await fn();await onChange()}catch(e){setError((e as Error).message)}finally{setBusy(false);inFlight.current=false}}
  return {busy,error,run};
}
export function SharedBrain({workspace}:{workspace:WorkspaceState|null}){const b=workspace?.brain,m=b?.snapshot;return <section className="merchant-tool brain-panel"><div className="card-head"><div><span className="card-kicker"><UiText text={"ONE CONNECTED BUSINESS BRAIN"}/></span><h2><UiText text={"Your whole team remembers the same business."}/></h2></div><Brain size={28}/></div><p><UiText text={"Each LLM teammate uses your approved playbook and the latest workspace records. Customer replies receive business facts; private owner records stay in your workspace."}/></p>
  <div className="brain-flow"><span><UiText text={"Approved facts"}/></span><ArrowRight size={16}/><span><UiText text={"Shared memory"}/></span><ArrowRight size={16}/><span><UiText text={"LLM reasoning"}/></span><ArrowRight size={16}/><span><UiText text={"Approved work + evidence"}/></span></div>
  <div className="merchant-metrics"><div><strong>{m?.acceptedOrders??0}</strong><span><UiText text={"Accepted orders"}/></span></div><div><strong>{m?.awaitingOwner??0}</strong><span><UiText text={"Need your attention"}/></span></div><div><strong>{money(m?.verifiedCollectionPaise??0)}</strong><span><UiText text={"Verified collections"}/></span></div><div><strong>{m?.reminders.scheduled??0}</strong><span><UiText text={"Scheduled reminders"}/></span></div></div>
  <div className="setup-box"><strong><UiText text={"Cognee memory"}/></strong><p><UiText text={workspace?.providers?.cognee?b?.cogneeState==='not_indexed'?'Save the approved playbook to Cognee in Business brief. All teammates can retrieve its verified sources.':'Your playbook has been sent for processing. Search its memory to check for verified source excerpts; changed facts need indexing again.':'The shared playbook is available now. Add the Cognee server settings to enable source retrieval across teammates.'}/></p></div>
  {!!m?.offers.length&&<><div className="stock-cards">{m.offers.map(o=><div key={o.id}><Package size={16}/><strong>{o.name}</strong><span>{o.quantity===null?'Add stock':`${o.quantity} available units`}</span><small>{o.reorderSuggested?'Reorder review needed':`Reorder threshold: ${o.reorderAt}`}</small></div>)}</div><p className="small-muted"><UiText text={"Available stock already excludes accepted product orders. Keep dispatch and payment separate; do not deduct the same order again."}/></p></>}
  <p className="small-muted"><UiText text={"Stock is owner-recorded. Your LLM teammates explain priorities and missing facts; delivery and accounting are separate."}/></p></section>}

export function Catalogue({token,workspace,ensureToken,onChange}:{token:string|null;workspace:WorkspaceState|null;ensureToken:()=>Promise<string>;onChange:()=>Promise<unknown>}){
const {t:localize}=useLanguage();

  const [offers,setOffers]=useState<Offer[]>(workspace?.commerce?.offers||[starter]),[approved,setApproved]=useState(false);const {busy,error,run}=useAction(onChange);
  const [hours,setHours]=useState<CommerceHours>(workspace?.commerce?.hours||{days:[1,2,3,4,5,6],opens:10,closes:19,noticeHours:1});
  const dirty=useRef(false),baselineHash=useRef(workspace?.commerce?.snapshotHash||'none');
  const serverSignature=workspace?.commerce?.snapshotHash||JSON.stringify({offers:workspace?.commerce?.offers||[],hours:workspace?.commerce?.hours||null});
  const observedSignature=useRef(serverSignature);
  const [catalogueChanged,setCatalogueChanged]=useState(false);
  function markDirty(){dirty.current=true;setApproved(false)}
  function reviewLatest(keepEdits:boolean){
    const latest=workspace?.commerce?.offers||[];
    if(keepEdits){setOffers(old=>old.map(offer=>{const saved=latest.find(o=>o.id===offer.id);return saved?{...offer,availableQuantity:saved.availableQuantity}:offer}));dirty.current=true;}
    else {setOffers(latest.length?latest:[starter]);setHours(workspace?.commerce?.hours||{days:[1,2,3,4,5,6],opens:10,closes:19,noticeHours:1});dirty.current=false;}
    baselineHash.current=workspace?.commerce?.snapshotHash||'none';observedSignature.current=serverSignature;setCatalogueChanged(false);setApproved(false);
  }
  const hoursValid=hours.days.length>0&&hours.closes>hours.opens&&Number.isInteger(hours.noticeHours)&&hours.noticeHours>=1&&hours.noticeHours<=72;
  useEffect(()=>{
    if(observedSignature.current===serverSignature)return;
    observedSignature.current=serverSignature;setApproved(false);
    if(dirty.current){setCatalogueChanged(true);return;}
    if(workspace?.commerce?.offers)setOffers(workspace.commerce.offers);
    if(workspace?.commerce?.hours)setHours(workspace.commerce.hours);
    baselineHash.current=workspace?.commerce?.snapshotHash||'none';setCatalogueChanged(false);
  },[serverSignature]);
  function edit(i:number,key:keyof Offer,value:unknown){markDirty();setOffers(old=>old.map((o,n)=>n===i?{...o,[key]:value}:o))}
  return <section className="merchant-tool"><div className="card-head"><div><span className="card-kicker"><UiText text={"PRODUCTS, SERVICES & STOCK"}/></span><h2><UiText text={"Give your team facts it can work with."}/></h2></div><Package size={25}/></div><p><UiText text={"Add up to 60 products or services. An empty stock or delivery field asks for your confirmation before a quote can be accepted."}/></p>{error&&<p className="workspace-error" role="alert">{error}</p>}{catalogueChanged&&<div className="setup-box" role="status"><strong><UiText text={"Your saved catalogue or stock changed while you were editing."}/></strong><p><UiText text={"Your unsaved edits are preserved. Review the latest saved quantities before approving again. Refresh stock keeps your price, terms and hours edits, and replaces unsaved stock values with the current available quantities."}/></p><details><summary><UiText text={"Latest saved offers"}/></summary>{workspace?.commerce?.offers.map(o=><p key={o.id}>{o.name} · {money(o.unitPricePaise)} · {o.availableQuantity===null?'Stock needs confirmation':`${o.availableQuantity} available units`}</p>)}</details><div className="builder-actions"><button className="text-button" disabled={busy} onClick={()=>reviewLatest(true)}><UiText text={"Refresh stock, keep my other edits"}/></button><button className="text-button" disabled={busy} onClick={()=>reviewLatest(false)}><UiText text={"Discard edits and reload saved offers"}/></button></div></div>}
    {offers.map((o,i)=><fieldset className="offer-editor" key={i} disabled={busy}><legend><UiText text={"Offer "}/>{i+1}</legend><div className="merchant-form-grid"><label><UiText text={"Name"}/><input value={o.name} onChange={e=>edit(i,'name',e.target.value)} maxLength={100}/></label><label><UiText text={"Type"}/><select value={o.kind} onChange={e=>{edit(i,'kind',e.target.value);if(e.target.value==='appointment')edit(i,'minimumQuantity',1)}}><option value="product"><UiText text={"Product"}/></option><option value="appointment"><UiText text={"Appointment"}/></option></select></label><label><UiText text={"Price per unit (₹)"}/><input type="number" min={1} max={100000} step="0.01" value={o.unitPricePaise/100} onChange={e=>edit(i,'unitPricePaise',Math.round(Number(e.target.value)*100))}/></label><label><UiText text={"Minimum quantity"}/><input type="number" min={1} max={100} value={o.minimumQuantity} onChange={e=>edit(i,'minimumQuantity',Number(e.target.value))}/></label>
    {o.kind==='product'?<><label><UiText text={"Available stock"}/><input type="number" min={0} max={1000} placeholder={localize("Unknown")} value={o.availableQuantity??''} onChange={e=>edit(i,'availableQuantity',e.target.value===''?null:Number(e.target.value))}/><small><UiText text={"Units available for new orders. Accepted orders reserve stock once."}/></small></label><label><UiText text={"Barcode · optional"}/><input value={o.barcode||''} maxLength={64} onChange={e=>edit(i,'barcode',e.target.value||undefined)}/></label><label><UiText text={"Reorder at"}/><input type="number" min={0} max={1000} value={o.reorderAt??2} onChange={e=>edit(i,'reorderAt',Number(e.target.value))}/></label></>:<label><UiText text={"Appointment length (minutes)"}/><input type="number" min={15} max={180} value={o.durationMinutes} onChange={e=>edit(i,'durationMinutes',Number(e.target.value))}/></label>}
    <label><UiText text={"Delivery / booking fee (₹)"}/><input type="number" min={0} max={10000} step="0.01" placeholder={localize("Unknown")} value={o.deliveryPaise===null?'':o.deliveryPaise/100} onChange={e=>edit(i,'deliveryPaise',e.target.value===''?null:Math.round(Number(e.target.value)*100))}/></label></div><label><UiText text={"Terms"}/><textarea rows={2} value={o.terms} maxLength={500} onChange={e=>edit(i,'terms',e.target.value)}/></label>{offers.length>1&&<button className="text-button" onClick={()=>{setOffers(offers.filter((_,n)=>n!==i));markDirty()}}><UiText text={"Remove offer"}/></button>}</fieldset>)}
    <fieldset className="offer-editor office-hours" disabled={busy}><legend><UiText text={"Business & booking hours · India time"}/></legend><div className="office-day-options">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day,index)=><label key={day}><input type="checkbox" checked={hours.days.includes(index)} onChange={e=>{setHours({...hours,days:e.target.checked?[...hours.days,index].sort():hours.days.filter(d=>d!==index)});markDirty()}}/>{day}</label>)}</div><div className="merchant-form-grid"><label><UiText text={"Opening hour"}/><select value={hours.opens} onChange={e=>{setHours({...hours,opens:Number(e.target.value)});markDirty()}}>{Array.from({length:23},(_,h)=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label><label><UiText text={"Closing hour"}/><select value={hours.closes} onChange={e=>{setHours({...hours,closes:Number(e.target.value)});markDirty()}}>{Array.from({length:23},(_,i)=>i+1).map(h=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label><label><UiText text={"Minimum booking notice (hours)"}/><input type="number" min={1} max={72} value={hours.noticeHours} onChange={e=>{setHours({...hours,noticeHours:Number(e.target.value)});markDirty()}}/></label></div>{!hoursValid&&<p role="alert"><UiText text={"Choose a working day, close after opening, and allow 1–72 hours of booking notice."}/></p>}<p className="small-muted"><UiText text={"These hours define when connected Calendar appointments may be offered. The teammate never promises stock or delivery from these hours."}/></p></fieldset>
    <div className="builder-actions"><button className="text-button" disabled={offers.length>=60||busy} onClick={()=>{setOffers([...offers,{...starter,id:`offer-${crypto.randomUUID().slice(0,8)}`,name:'New offer'}]);markDirty()}}><UiText text={"Add another offer +"}/></button></div><label className="approval-checkbox"><input type="checkbox" checked={approved} disabled={catalogueChanged||busy} onChange={e=>setApproved(e.target.checked)}/> <UiText text={"I approve these prices, recorded stock, hours and terms."}/></label><button className="button button-dark" disabled={busy||!approved||!hoursValid||catalogueChanged} onClick={()=>run(async()=>{if(catalogueChanged)return;const currentToken=await ensureToken();await api.commerceSetup(currentToken,offers,hours,baselineHash.current);setApproved(false);const saved=await api.workspace(currentToken);baselineHash.current=saved.commerce?.snapshotHash||'none';observedSignature.current=saved.commerce?.snapshotHash||JSON.stringify({offers:saved.commerce?.offers||[],hours:saved.commerce?.hours||null});dirty.current=false;setCatalogueChanged(false);if(saved.commerce?.offers)setOffers(saved.commerce.offers);if(saved.commerce?.hours)setHours(saved.commerce.hours)})}><UiText text={busy?'Saving…':'Save approved offers'}/> <Check size={16}/></button>
    <div className="setup-box"><CalendarDays size={20}/><strong><UiText text={"Appointments in your calendar"}/></strong><p><UiText text={"Save your business and booking hours above. Connect Google Calendar, then approve your writable primary calendar. KaamSet checks real availability before confirming a booking."}/></p><button className="button button-dark" disabled={busy||!token||!workspace?.commerce||!workspace.connections.some(c=>c.toolkit==='googlecalendar'&&c.status==='connected')} onClick={()=>run(()=>api.approveCalendar(token!))}><UiText text={workspace?.commerce?.calendar?'Recheck primary calendar':'Approve my primary calendar'}/></button>{workspace?.commerce?.calendar&&<p><UiText text={"Approved: "}/>{workspace.commerce.calendar.label}</p>}</div>
  </section>;
}

export function MilanScheduler({token,workspace,onChange,onBuild,onPair}:{token:string|null;workspace:WorkspaceState|null;onChange:()=>Promise<unknown>;onBuild:()=>void;onPair:()=>void}){
  const {busy,error,run}=useAction(onChange);const [contacts,setContacts]=useState<{id:string;name:string}[]>([]),[contact,setContact]=useState(''),[message,setMessage]=useState('Namaste! Aap payment karne ke baad reference share kar denge? Agar koi help chahiye toh batayein. Dhanyavaad.'),[consent,setConsent]=useState(false),[order,setOrder]=useState('');
  const [at,setAt]=useState(()=>new Date(Date.now()+19800000+300000).toISOString().slice(0,16));const milan=workspace?.blueprints.find(b=>b.state==='active'&&b.plan.skills.includes('whatsapp_schedule'));
  const reminderTime=new Date(`${at}:00+05:30`).getTime(),validReminderTime=Number.isFinite(reminderTime)&&reminderTime>Date.now();
  const [draftId,setDraftId]=useState('');const draft=workspace?.tasks.find(t=>t.id===draftId);
  useEffect(()=>{if(draft?.state==='completed'&&draft.result&&draft.result.output.length<=1500){setMessage(draft.result.output);setConsent(false);setDraftId('')}},[draft?.state,draft?.result]);
  return <section className="merchant-tool milan-panel"><div className="milan-heading"><PixelTeammate id="milan" state={busy?'working':'idle'}/><div><span className="card-kicker"><UiText text={"MEET MILAN · YOUR PERSONAL PA"}/></span><h2><UiText text={"“Yeh kaam yaad se kar dena.”"}/></h2><p><UiText text={"Approve a person, a personal message and a time. Milan takes care of the reminder from the cloud."}/></p></div></div>{error&&<p className="workspace-error" role="alert">{error}</p>}
    {!milan&&<div className="setup-box"><strong><UiText text={"Give Milan a scheduled-reminder job first."}/></strong><p><UiText text={"Review the playbook, pair WhatsApp and activate the checked teammate."}/></p><button className="button button-dark" onClick={onBuild}><UiText text={"Set up Milan "}/><ArrowRight size={16}/></button></div>}
    <div className="builder-actions"><button className="text-button" onClick={onPair}><UiText text={"Pair WhatsApp"}/></button><button className="text-button" disabled={!token||busy||!workspace?.whatsappLinked} onClick={()=>run(async()=>{await api.whatsapp(token!);const r=await api.reminderContacts(token!);setContacts(r.contacts);setContact(r.contacts[0]?.id||'');setConsent(false)})}><UiText text={"Load my recent contacts"}/></button></div><p className="small-muted"><UiText text={"Existing individual chats only. Ask the contact to message the paired number if their chat is missing. No groups or bulk outreach."}/></p>
    <div className="merchant-form-grid"><label><UiText text={"Person"}/><select value={contact} onChange={e=>{setContact(e.target.value);setConsent(false);setDraftId('')}}><option value=""><UiText text={"Choose a contact"}/></option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><UiText text={"Send at (India time)"}/><input type="datetime-local" value={at} onChange={e=>{setAt(e.target.value);setConsent(false)}}/></label></div><label><UiText text={"Exact message"}/><textarea rows={4} maxLength={1500} value={message} onChange={e=>{setMessage(e.target.value);setConsent(false);setDraftId('')}}/></label><label><UiText text={"Stop after a verified payment (optional)"}/><select value={order} onChange={e=>{setOrder(e.target.value);setConsent(false)}}><option value=""><UiText text={"General personal reminder"}/></option>{workspace?.commerce?.orders.filter(o=>o.customerAcceptedAt).map(o=><option value={o.id} key={o.id}>{o.name} · {money(o.amountPaise)}</option>)}</select></label>
    <button className="text-button" disabled={busy||!token||!milan||!contact||!!draftId&&['queued','working'].includes(draft?.state||'queued')} onClick={()=>run(async()=>{const r=await api.runTeammate(token!,milan!.id,`Draft exactly one personal WhatsApp reminder for ${contacts.find(c=>c.id===contact)?.name||'the selected contact'} in the owner's language. The output field must contain only the send-ready message, under 700 characters. Follow the approved playbook. Ask for missing facts; do not invent payment amounts or prior commitments. Intended message: ${message}`);setDraftId(r.id)})}><UiText text={draftId&&['queued','working'].includes(draft?.state||'queued')?'Milan is drafting in the cloud…':'Ask Milan to personalise this draft'}/></button>{draft?.state==='failed'&&<p><UiText text={"Milan could not complete this draft. Review Work & results before trying again."}/></p>}
    {!validReminderTime&&<p role="alert"><UiText text={"Choose a future reminder time in India time."}/></p>}<label className="approval-checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> <UiText text={"This contact expects this message. I approve the exact recipient, text and time."}/></label><button className="button button-primary" disabled={busy||!token||!milan||!contact||!consent||message.trim().length<3||!validReminderTime} onClick={()=>run(async()=>{await api.scheduleReminder(token!,{blueprintId:milan!.id,contactId:contact,message,at:new Date(`${at}:00+05:30`).toISOString(),consentConfirmed:true,...(order?{orderId:order}:{})});setConsent(false)})}><UiText text={"Schedule with Milan "}/><Send size={16}/></button><p className="small-muted"><UiText text={"Your browser can close. Quiet hours 10pm–7am IST delay sends. Guest jobs last within the 24-hour workspace. Keep the cloud session paired."}/></p>
    <div className="reminder-list">{workspace?.reminders?.slice().reverse().map(r=><article key={r.id}><div><Clock3 size={16}/><strong>{r.contactName}</strong><span className="readiness-pill">{r.state.replaceAll('_',' ')}</span></div><p>{r.message}</p><small>{when(r.at)}</small>{r.reason&&<p>{r.reason}</p>}{r.providerMessageId&&<p className="small-muted"><UiText text={"WhatsApp receipt: "}/>{r.providerMessageId}</p>}{['scheduled','waiting_owner'].includes(r.state)&&<button className="text-button" disabled={busy||!token} onClick={()=>run(()=>api.cancelReminder(token!,r.id))}><UiText text={"Cancel message"}/></button>}</article>)}</div>
  </section>;
}

export function OrderDesk({token,workspace,onChange}:{token:string|null;workspace:WorkspaceState|null;onChange:()=>Promise<unknown>}){
  const {busy,error,run}=useAction(onChange);const offers=workspace?.commerce?.offers||[];const [offer,setOffer]=useState(''),[quantity,setQuantity]=useState(1),[url,setUrl]=useState(''),[fee,setFee]=useState<Record<string,string>>({}),[copied,setCopied]=useState(false);
  useEffect(()=>{if(offers.length&&!offers.some(o=>o.id===offer)){setOffer(offers[0].id);setQuantity(offers[0].minimumQuantity)}},[offers.map(o=>o.id).join('|'),offer]);
  return <section className="merchant-tool"><div className="card-head"><div><span className="card-kicker"><UiText text={"MEERA’S ORDER DESK"}/></span><h2><UiText text={"A clear quote. An explicit yes."}/></h2></div><PixelTeammate id="ma"/></div><p><UiText text={"Create an exact quote from approved offers. Your customer opens a private link, accepts the amount, and picks a live calendar slot for an appointment."}/></p>{error&&<p className="workspace-error" role="alert">{error}</p>}
    {!offers.length?<div className="setup-box"><UiText text={"Save approved products or services in Business brief to start."}/></div>:<><div className="merchant-form-grid"><label><UiText text={"Offer"}/><select value={offer} onChange={e=>{setOffer(e.target.value);setQuantity(offers.find(o=>o.id===e.target.value)?.minimumQuantity||1)}}>{offers.map(o=><option value={o.id} key={o.id}>{o.name} · {money(o.unitPricePaise)}</option>)}</select></label><label><UiText text={"Quantity"}/><input type="number" min={offers.find(o=>o.id===offer)?.minimumQuantity||1} max={1000} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label></div><button className="button button-dark" disabled={busy||!token||!offer} onClick={()=>run(async()=>{const q=await api.quote(token!,offer,quantity);setUrl(q.state==='quoted'?q.url:'');setCopied(false)})}><UiText text={"Prepare exact quote "}/><ArrowRight size={16}/></button></>}
    {url&&<div className="quote-share"><QRCodeSVG value={url} size={140} marginSize={3}/><div><strong><UiText text={"Customer quote link"}/></strong><p><UiText text={"Share this link with the intended customer. It gives access to this quote only."}/></p><a href={url} target="_blank" rel="noreferrer"><UiText text={"Open customer quote"}/></a><button className="text-button" onClick={()=>run(async()=>{await navigator.clipboard.writeText(url);setCopied(true)})}><Copy size={15}/><UiText text={copied?'Copied':'Copy link'}/></button></div></div>}
    <div className="order-list">{workspace?.commerce?.orders.slice().reverse().map(o=><article key={o.id}><div className="task-result-head"><strong>{o.name} × {o.quantity}</strong><span className="readiness-pill">{o.state.replaceAll('_',' ')}</span></div><p>{money(o.amountPaise)} · {o.paymentState?.replaceAll('_',' ')||'Payment not requested'}</p>{o.reason&&<p>{o.reason}</p>}{!!o.calendarReceipt&&<p className="small-muted"><UiText text={"Calendar provider receipt saved."}/></p>}{o.state==='awaiting_owner'&&<div><label><UiText text={"Approved delivery / booking fee (₹)"}/><input type="number" min={0} max={10000} step="0.01" value={fee[o.id]??''} onChange={e=>setFee({...fee,[o.id]:e.target.value})}/></label><button className="button button-dark" disabled={busy||!token||fee[o.id]===undefined||fee[o.id]===''} onClick={()=>run(async()=>{const q=await api.approveQuote(token!,o.id,Math.round(Number(fee[o.id])*100));setUrl(q.url)})}><UiText text={"Confirm stock and this fee"}/></button></div>}{(['uncertain','confirmed'].includes(o.state)&&(o.kind==='appointment'||(!o.paymentMethod||o.paymentMethod==='paytm')&&!!o.paymentState&&!['setup_needed'].includes(o.paymentState)))&&<button className="text-button" disabled={busy||!token} onClick={()=>run(()=>api.verifyOrder(token!,o.id))}><UiText text={"Verify provider result"}/></button>}{o.state==='confirmed'&&(!o.paymentMethod||o.paymentMethod==='paytm')&&workspace?.paymentSetup?.configured&&!o.paymentUrl&&<button className="text-button" disabled={busy||!token} onClick={()=>run(()=>api.orderPayment(token!,o.id))}><UiText text={"Create Paytm payment request"}/></button>}{o.paymentUrl&&<a href={o.paymentUrl} target="_blank" rel="noreferrer"><UiText text={"Open Paytm checkout"}/></a>}</article>)}</div><p className="small-muted"><UiText text={"Payment requests need Paytm staging setup. An accepted order or verified payment does not mark delivery complete."}/></p>
  </section>;
}

