import {useState} from 'react';
import {ArrowUpRight,Link2,RefreshCw,Send} from 'lucide-react';
import type {LabConversation} from './merchant-lab-types';
import {merchantLabApi,labTokenKey} from './merchant-lab-api';
export default function MerchantLabLive({conversation}:{conversation:LabConversation}){
 const [candidates,setCandidates]=useState<{id:string;channel:string;customerName:string;preview:string;createdAt:string}[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState(''),[bound,setBound]=useState(false),[approved,setApproved]=useState(false);
 const token=localStorage.getItem(labTokenKey),message=conversation.messages.filter(m=>m.direction==='outbound'&&m.jobId).at(-1);
 async function act(fn:()=>Promise<unknown>){if(busy||!token)return;setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details className="lab-live-binding"><summary><Link2 size={15}/>Use an eligible real test conversation</summary><p>Connect your own account and start its live reply team first. Choose a genuine inbound conversation that needs owner review. Fictional customer consent never authorizes a live reply.</p><a className="lab-record-link" href="/?merchantLab=1&desk=connections">Open real account connections <ArrowUpRight size={15}/></a>{error&&<p role="alert" className="lab-alert">{error}</p>}{notice&&<p role="status" className="lab-footnote">{notice}</p>}<button className="lab-button lab-secondary" disabled={busy} onClick={()=>void act(async()=>{const result=await merchantLabApi.candidates(token!);const expected=conversation.channel==='instagram'?'instagram_dm':conversation.channel;setCandidates(result.candidates.filter(c=>c.channel===expected));setNotice(result.note)})}><RefreshCw size={14}/>Check eligible inbound conversations</button>{!!candidates.length&&<><label>Authorized live test conversation<select value={selected} onChange={e=>{setSelected(e.target.value);setBound(false);setApproved(false)}}><option value="">Choose a genuine inbound message</option>{candidates.map(c=><option value={c.id} key={c.id}>{c.customerName} · {c.preview.slice(0,80)}</option>)}</select></label><button className="lab-button lab-secondary" disabled={busy||!selected} onClick={()=>void act(async()=>{await merchantLabApi.bind(token!,conversation.id,selected);setBound(true);setNotice('Genuine identity mapping saved. Review the exact message below before a live reply.');})}>Bind this test conversation</button></>}{bound&&message&&<><h3>Exact message for the live recipient</h3><p className="lab-pre-wrap">{message.text}</p><label className="lab-authorization"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>I authorize this exact reply to the selected genuine test conversation.</label><button className="lab-button lab-primary" disabled={busy||!approved} onClick={()=>void act(async()=>{await merchantLabApi.liveReply(token!,conversation.id,message.id);setApproved(false);setNotice('Live reply submitted to the existing channel executor. Open Customer desk for the genuine provider receipt or delivery issue.');})}><Send size={14}/>Approve live test reply</button></>}</details>
}
