import {useCallback,useEffect,useRef,useState} from 'react';
import MerchantLab from './MerchantLab';
import type {MerchantLabView,LabPresenterInput} from './merchant-lab-types';
import {labTokenKey,merchantLabApi,MerchantLabApiError} from './merchant-lab-api';
import SiaAssistant,{showSia} from './SiaAssistant';
import {api} from './api';
export default function MerchantLabContainer({embedded=false}:{embedded?:boolean}){
 const [token,setToken]=useState(()=>localStorage.getItem(labTokenKey)),[state,setState]=useState<MerchantLabView|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[syncing,setSyncing]=useState(false);
 const data=useRef(state),requestSequence=useRef(0),appliedSequence=useRef(0),active=useRef(true),reading=useRef(false),mutation=useRef(false),currentToken=useRef(token),helpToken=useRef<Promise<string>|null>(null);data.current=state;currentToken.current=token;
 const refresh=useCallback(async(force=false)=>{if(!token||reading.current)return;reading.current=true;const seq=++requestSequence.current;try{const result=await merchantLabApi.read(token,force?undefined:data.current?.version,data.current?.generation);if(active.current&&token===currentToken.current&&seq>=appliedSequence.current){appliedSequence.current=seq;if(!('unchanged' in result)&&!(data.current?.generation===result.generation&&data.current.version>result.version))setState(result);setSyncing(false);setError('');}}catch(e){if(active.current&&token===currentToken.current){if(e instanceof MerchantLabApiError&&[401,403,404].includes(e.status)){localStorage.removeItem(labTokenKey);setToken(null);setState(null);setSyncing(false);setError('This prepared session is unavailable or expired. Open a new prepared store.');}else{setSyncing(true);setError((e as Error).message);}}}finally{reading.current=false;}},[token]);
 useEffect(()=>{active.current=true;void refresh(true);let polls=0;const timer=setInterval(()=>{if(!document.hidden){polls++;const awaitingMemory=data.current?.connection.state==='connected'&&['processing','not_indexed'].includes(data.current.cognee.state);void refresh(awaitingMemory&&polls%10===0)}},1000);const visible=()=>{if(!document.hidden)void refresh(true)};window.addEventListener('focus',visible);document.addEventListener('visibilitychange',visible);return()=>{active.current=false;clearInterval(timer);window.removeEventListener('focus',visible);document.removeEventListener('visibilitychange',visible)}},[refresh]);
 async function act(label:string,fn:()=>Promise<unknown>){if(mutation.current)return;mutation.current=true;appliedSequence.current=++requestSequence.current;setBusy(label);setError('');try{await fn();await refresh(true);}catch(e){setError((e as Error).message);showSia('general',(e as Error).message);}finally{setBusy('');mutation.current=false;}}
 async function open(){await act('Preparing the stored business',async()=>{const created=await merchantLabApi.prepare(token);localStorage.setItem(labTokenKey,created.token);setToken(created.token);setState(created.lab);});}
 const presenter=(input:LabPresenterInput)=>act('Applying the demo input',()=>merchantLabApi.presenter(token!,input));
 return <><MerchantLab embedded={embedded} state={state} busy={busy} error={error} syncing={syncing} onOpenPrepared={open} onConnect={()=>act('Authorizing and synchronizing demo records',()=>merchantLabApi.connect(token!))} onRunJob={id=>act('Submitting the job to the cloud',()=>merchantLabApi.run(token!,id))} onPresenter={presenter} onRefresh={()=>refresh(true)} onDownload={kind=>act('Preparing the synthetic report',()=>merchantLabApi.download(token!,kind))} onOpenWorkspace={()=>{window.location.href='/?merchantLab=1'}}/>{!embedded&&<SiaAssistant getToken={()=>{if(token)return Promise.resolve(token);helpToken.current||=api.onboardingSession().then(r=>r.token).catch(e=>{helpToken.current=null;throw e;});return helpToken.current;}}/>}</>;
}
