import {UiText} from './Language';
import {useEffect,useRef,useState} from 'react';
import {Check,ExternalLink,Mic,Square,Upload} from 'lucide-react';
import {api,type ContentPost,type DemoState,type Payment,type Teammate} from './api';
import {useLanguage} from './Language';
import {BusinessPhotoLibrary} from './BusinessAssets';
import {showSia} from './SiaAssistant';

const asBase64=(blob:Blob)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(blob)});
let voiceLease:symbol|null=null;

export function VoiceInput({token,enabled,onText,onError,getToken,label='Speak your job'}:{token:string|null;enabled:boolean;onText:(s:string)=>void;onError:(s:string)=>void;getToken?:()=>Promise<string>;label?:string}){
  const {t}=useLanguage();
  const lease=useRef(Symbol('voice'));
  const [recording,setRecording]=useState(false),[busy,setBusy]=useState(false);
  const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),inFlight=useRef(false),mounted=useRef(true);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;if(timer.current)clearTimeout(timer.current);if(recorder.current?.state==='recording'){recorder.current.onstop=null;recorder.current.stop()}stream.current?.getTracks().forEach(t=>t.stop());if(voiceLease===lease.current)voiceLease=null}},[]);
  async function start(){if((!token&&!getToken)||inFlight.current)return;inFlight.current=true;setBusy(true);try{
    if(voiceLease&&voiceLease!==lease.current)throw new Error('Finish the current recording before speaking into another field.');voiceLease=lease.current;
    if(!navigator.mediaDevices||!window.MediaRecorder)throw new Error('Voice recording is unavailable here. You can type your request.');
    const mime=['audio/webm','audio/ogg'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime)throw new Error('Please type your request in this browser.');
    const input=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current){input.getTracks().forEach(t=>t.stop());return}stream.current=input;
    const speechToken=token||await getToken!();if(!mounted.current){input.getTracks().forEach(t=>t.stop());return}
    const r=new MediaRecorder(input,{mimeType:mime,audioBitsPerSecond:64000});recorder.current=r;const chunks:Blob[]=[];
    r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};r.onstop=async()=>{input.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current);if(!mounted.current)return;setRecording(false);setBusy(true);
      try{const audio=await asBase64(new Blob(chunks,{type:mime}));const result=await api.speech(speechToken,audio,mime);if(mounted.current)onText(result.transcript)}catch(e){if(mounted.current)onError((e as Error).message)}finally{inFlight.current=false;if(voiceLease===lease.current)voiceLease=null;if(mounted.current)setBusy(false)}};
    r.start();setRecording(true);setBusy(false);timer.current=setTimeout(()=>{if(r.state==='recording')r.stop()},25000);
  }catch(e){stream.current?.getTracks().forEach(t=>t.stop());inFlight.current=false;if(voiceLease===lease.current)voiceLease=null;if(mounted.current){setBusy(false);onError((e as Error).name==='NotAllowedError'?'Microphone access was declined. You can type your job instead.':(e as Error).message)}}}
  if(!enabled)return null;
  return <button type="button" className="text-button voice-input" disabled={busy||(!token&&!getToken)} onClick={()=>recording?recorder.current?.stop():start()}>{recording?<Square size={16}/>:<Mic size={16}/>} {t(busy?'Preparing voice…':recording?'Stop recording (25s max)':label)}</button>;
}

export function ContentStudio({token,teammates,posts,onChange,onBuild,instagramReady=false,onConnect}:{token:string|null;teammates:Teammate[];posts:ContentPost[];onChange:()=>Promise<unknown>;onBuild?:()=>void;instagramReady?:boolean;onConnect?:()=>void}){
const {t:localize}=useLanguage();

  const [id,setId]=useState(''),[headline,setHeadline]=useState(''),[caption,setCaption]=useState(''),[photo,setPhoto]=useState(''),[rights,setRights]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [schedules,setSchedules]=useState<Record<string,string>>({}),[readingPhoto,setReadingPhoto]=useState(false);
  const [previews,setPreviews]=useState<Record<string,string>>({});
  const [activationApproved,setActivationApproved]=useState(false);
  const uploader=useRef<HTMLInputElement>(null),inFlight=useRef(false);
  const available=teammates.filter(b=>b.state==='active'&&b.plan.skills.some(s=>['content_draft','instagram_publish'].includes(s)))
    .sort((a,b)=>Number(b.plan.skills.includes('instagram_publish'))-Number(a.plan.skills.includes('instagram_publish')));
  const selected=available.find(b=>b.id===id)||(!id?available[0]:undefined);
  const pendingPublisher=teammates.find(b=>b.state!=='active'&&b.plan.skills.includes('instagram_publish'));
  async function act(fn:()=>Promise<void>){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{await fn();await onChange()}catch(e){setError((e as Error).message)}finally{setBusy(false);inFlight.current=false}}
  useEffect(()=>{if(id&&!available.some(b=>b.id===id)){setId('');setRights(false)}},[available.map(b=>b.id).join('|'),id]);
  useEffect(()=>{setActivationApproved(false)},[pendingPublisher?.id,pendingPublisher?.revision]);
  useEffect(()=>{if(!token)return;let cancelled=false;Promise.allSettled(posts.map(async p=>{const r=await api.postPreview(token,p.id);return [p.id,r.url] as const})).then(items=>{if(!cancelled)setPreviews(old=>({...old,...Object.fromEntries(items.filter(r=>r.status==='fulfilled').map(r=>(r as PromiseFulfilledResult<readonly [string,string]>).value))}))});return()=>{cancelled=true}},[token,posts.map(p=>p.id).join(',')]);
  return <section className="content-studio"><span className="card-kicker"><UiText text={"RIYA’S CONTENT STUDIO"}/></span><h2><UiText text={"A real product photo. An exact approval."}/></h2><p><UiText text={"Prepare a branded static post for your connected Instagram Business or Creator account. Review the exact image and caption before publishing."}/></p>
    {error&&<div className="workspace-error" role="alert">{error}</div>}
    {pendingPublisher&&<div className="setup-box"><strong><UiText text={"Your publishing job is saved. Review it and start Riya."}/></strong><p>{pendingPublisher.plan.outcome}</p><ul>{pendingPublisher.plan.rules.map(rule=><li key={rule}>{rule}</li>)}</ul>{!!pendingPublisher.feasibility.blockers.length&&<><strong><UiText text={"Complete this setup first"}/></strong><ul>{pendingPublisher.feasibility.blockers.map(blocker=><li key={blocker}>{blocker}</li>)}</ul></>}
      <label className="approval-checkbox"><input type="checkbox" checked={activationApproved} onChange={e=>setActivationApproved(e.target.checked)}/><span><UiText text={"I approve this saved job and its rules. Each post still needs my exact image and caption approval."}/></span></label>
      <button className="button button-primary" disabled={busy||!token||!activationApproved||pendingPublisher.feasibility.state!=='ready_to_test'} onClick={()=>act(async()=>{if(!token)return;await api.teammateControl(token,pendingPublisher,'activate');setActivationApproved(false)})}><Check size={16}/><UiText text={"Activate reviewed publishing job"}/></button>{onBuild&&<button className="text-button" onClick={onBuild}><UiText text={"Edit Riya’s job modules"}/></button>}</div>}
    {!available.length&&!pendingPublisher&&<div className="setup-box"><strong><UiText text={"Activate your ready content teammate first."}/></strong><p><UiText text={"Set up Riya, connect a professional Instagram account and review her publishing job before preparing a post."}/></p>{onBuild&&<button className="button button-dark" onClick={onBuild}><UiText text={"Set up Riya’s publishing team"}/></button>}</div>}
    {!instagramReady&&<div className="setup-box"><strong><UiText text={"Connect Instagram before preparing a publishable preview."}/></strong><p><UiText text={"Use your Business or Creator account. Your teammate's text drafts are available in My work."}/></p>{onConnect&&<button className="button button-dark" onClick={onConnect}><UiText text={"Connect my Instagram"}/></button>}</div>}
    {instagramReady&&!!available.length&&!available.some(b=>b.plan.skills.includes('instagram_publish'))&&<div className="setup-box"><strong><UiText text={"Instagram is connected. Publishing still needs your approval."}/></strong><p><UiText text={"Riya’s current job writes drafts. Enable Publish approved Instagram posts, review the job and activate it to publish from this studio."}/></p>{onBuild&&<button className="button button-primary" onClick={onBuild}><UiText text={"Enable Riya’s publishing job"}/></button>}</div>}
    <div className="studio-layout"><div><fieldset disabled={busy||readingPhoto} className="studio-fields"><label htmlFor="content-teammate"><UiText text={"Active content teammate"}/></label><select id="content-teammate" value={selected?.id||''} onChange={e=>{setId(e.target.value);setRights(false)}}><option value=""><UiText text={"Select a teammate"}/></option>{available.map(b=><option key={b.id} value={b.id}>{b.plan.name}</option>)}</select>
    <label htmlFor="post-headline"><UiText text={"Headline on image"}/></label><input id="post-headline" maxLength={80} value={headline} onChange={e=>{setHeadline(e.target.value);setRights(false)}}/><label htmlFor="post-caption"><UiText text={"Exact caption"}/></label><textarea id="post-caption" rows={5} maxLength={2200} value={caption} onChange={e=>{setCaption(e.target.value);setRights(false)}}/>
    <BusinessPhotoLibrary token={token} onSelect={photo=>{setPhoto(photo);setRights(false)}} onError={setError}/>
    <input hidden ref={uploader} type="file" accept="image/jpeg,image/png" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setRights(false);setError('');if(!['image/jpeg','image/png'].includes(f.type)||f.size>1500000){setError('Choose a JPEG or PNG under 1.5 MB.');return}setReadingPhoto(true);try{setPhoto(await asBase64(f))}catch{setError('The photo could not be read. Choose it again.')}finally{setReadingPhoto(false)}}}/>
    <button type="button" className="text-button" onClick={()=>uploader.current?.click()}><Upload size={16}/><UiText text={photo?'Replace product photo':'Upload product photo'}/></button>{photo&&<img className="product-photo" src={`data:image/png;base64,${photo}`} alt={localize("Your uploaded product")}/>}
    <label className="approval-checkbox"><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/><span><UiText text={"I own or have permission to use this photo and content."}/></span></label></fieldset>
    {readingPhoto&&<p role="status"><UiText text={"Preparing your photo for review…"}/></p>}
    <button className="button button-dark" disabled={busy||readingPhoto||!token||!instagramReady||!rights||!photo||!selected||!headline.trim()||!caption.trim()} onClick={()=>act(async()=>{if(!token||!selected)return;await api.preparePost(token,{blueprintId:selected.id,headline:headline.trim(),caption:caption.trim(),photo,rightsConfirmed:rights});setRights(false)})}><UiText text={busy?'Preparing…':'Prepare exact preview'}/></button><p className="small-muted"><UiText text={"Add a headline, caption and photo, then review the content permission to prepare your preview."}/></p></div>
    <div className="studio-note"><img src="/crew/riya.png" alt={localize("Riya, your Instagram teammate")}/><h3><UiText text={"Approval belongs to you"}/></h3><p><UiText text={"Publishing runs on the cloud worker. If a provider response is uncertain, Riya waits for verification and avoids sending the post again."}/></p><p><UiText text={"Routine comments and DMs need separate permissions and a verified live channel."}/></p></div></div>
    {posts.slice().reverse().map(p=>{const schedule=schedules[p.id]||'',time=schedule?new Date(`${schedule}:00+05:30`).getTime():null;const publishingTeammate=teammates.find(b=>b.id===p.blueprintId&&b.state==='active'&&b.plan.skills.includes('instagram_publish'));const validTime=!schedule||(time!==null&&Number.isFinite(time)&&time>Date.now());const reviewable=['draft','waiting_owner','failed'].includes(p.state);return <article className="prepared-post" key={p.id}><img src={previews[p.id]||p.imageUrl} alt={p.headline}/><div><span className={`readiness-pill ${p.state==='published'?'ready':''}`}>{p.state.replaceAll('_',' ')}</span><h3>{p.headline}</h3><p className="result-prose">{p.caption}</p>{p.reason&&<p className="setup-box" role="status">{p.reason}</p>}{['queued','creating','container_ready','publishing'].includes(p.state)&&<p className="small-muted" role="status"><UiText text={"Riya is processing your approved post in the cloud. A verified Instagram link appears after the provider confirms publishing."}/></p>}{reviewable&&<>{!publishingTeammate&&<div className="setup-box"><p><UiText text={"Enable and activate publishing on this Riya team, then return to approve this exact preview."}/></p>{onBuild&&<button className="text-button" onClick={onBuild}><UiText text={"Review Riya’s publishing job"}/></button>}</div>}<label htmlFor={`schedule-${p.id}`}><UiText text={"Publish now, or select a time (India time)"}/></label><input id={`schedule-${p.id}`} type="datetime-local" value={schedule} disabled={busy} onChange={e=>setSchedules(old=>({...old,[p.id]:e.target.value}))}/>{!validTime&&<p role="alert"><UiText text={"Choose a future time, or clear it to publish now."}/></p>}<button className="button button-primary" disabled={busy||!token||!instagramReady||!publishingTeammate||!validTime} onClick={()=>act(async()=>{if(token)await api.approvePost(token,p,time??Date.now())})}><Check size={16}/><UiText text={p.state==='draft'?"Approve this exact post":"Review & approve this exact post again"}/></button></>}{['uncertain','publishing'].includes(p.state)&&<button className="text-button" disabled={busy||!token} onClick={()=>act(async()=>{if(token)await api.verifyPost(token,p.id)})}><UiText text={"Check provider evidence"}/></button>}{p.permalink&&<a className="text-button" href={p.permalink} target="_blank" rel="noreferrer"><UiText text={"View verified Instagram post "}/><ExternalLink size={16}/></a>}{p.logIds.length>0&&<details><summary><UiText text={"Provider evidence"}/></summary><code>{p.logIds.join('\n')}</code></details>}</div></article>})}
  </section>;
}

export function BusinessMemory({token,enabled,onChange}:{token:string|null;enabled:boolean;onChange?:()=>Promise<unknown>}){
  const {t}=useLanguage(),[query,setQuery]=useState('What are the approved prices and minimum order?'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[excerpts,setExcerpts]=useState<string[]>([]);
  const locked=useRef(false);
  async function run(search:boolean){if(!token||locked.current)return;locked.current=true;setBusy(true);setMessage('');setError('');setExcerpts([]);try{
    if(search){const r=await api.recall(token,query);if(r.state==='index_failed')showSia('memory','The last memory upload did not finish. Choose Save latest sources to memory to retry.');if(r.state==='provider_busy')showSia('memory','Cognee is busy. Wait before searching again. Your saved facts are intact.');setExcerpts(r.excerpts);setMessage(r.excerpts.length?'Verified excerpts from your saved sources':r.state==='processing'?'Your latest sources are being indexed. Wait a moment, then check again. Your team can still use your saved business facts.':r.state==='index_failed'?'The last memory upload did not finish. Choose Save latest sources to memory to retry.':r.state==='provider_busy'?'Cognee is busy. Wait before searching again. Your saved facts are intact.':'Search finished, but found no exact source excerpt for this question. Try a more specific question.');}
    else{const r=await api.remember(token);setMessage(['ready','source_verified'].includes(r.state)?'Your latest sources are already indexed. You can search now.':'Your latest sources are being indexed. Wait a moment, then check again. Your team can still use your saved business facts.');}
    await onChange?.();
  }catch(e){setError((e as Error).message)}finally{setBusy(false);locked.current=false}}
  return <section className="business-memory"><h3>{t('Search your business memory')}</h3><p>{t('Cognee retrieves exact excerpts from your approved facts and reviewed private records. Imported records remain reported history.')}</p>{!enabled?<p>{t('Advanced memory search is not configured. Your team can still use your saved business facts.')}</p>:<><button type="button" className="text-button" disabled={!token||busy} onClick={()=>void run(false)}>{t('Save latest sources to memory')}</button><label htmlFor="memory-query">{t('Question about your facts')}</label><input id="memory-query" value={query} onChange={e=>setQuery(e.target.value)} minLength={3} maxLength={1000}/><button type="button" className="button button-dark" disabled={!token||busy||query.trim().length<3} onClick={()=>void run(true)}>{t(busy?'Checking memory…':'Find source excerpts')}</button><p role="status">{t(message)}</p>{error&&<p className="office-error" role="alert">{t(error)}</p>}{excerpts.map((s,i)=><blockquote key={i}>{s}</blockquote>)}</>}</section>;
}

export function PaymentPanel({token,state,configured}:{token:string;state:DemoState;configured:boolean}){
  const [payments,setPayments]=useState<Payment[]>([]),[accepted,setAccepted]=useState<Record<string,boolean>>({}),[busy,setBusy]=useState(''),[error,setError]=useState('');
  const bookings=state.bookings.filter(b=>b.status==='confirmed');
  useEffect(()=>{api.workspace(token).then(w=>setPayments(w.payments||[])).catch(()=>{})},[token,state.bookings.length]);
  async function run(id:string,verify=false){setBusy(id);setError('');try{const p=verify?await api.verifyPayment(token,id):await api.payment(token,id);setPayments(old=>[...old.filter(x=>x.id!==p.id),p])}catch(e){setError((e as Error).message)}finally{setBusy('')}}
  return <section className="payment-panel"><span className="paytm-wordmark"><UiText text={"pay"}/><span><UiText text={"tm"}/></span></span><h3><UiText text={"Test payment requests"}/></h3><p><UiText text={configured?'After the customer accepts the visit fee, create a Paytm staging request. Server verification confirms payment.':'Paytm staging is awaiting merchant test credentials. Booking remains available.'}/></p>{error&&<div className="workspace-error" role="alert">{error}</div>}{configured&&bookings.map(b=>{const p=payments.find(p=>p.bookingId===b.id),service=state.session.merchant.services.find(s=>s.code===b.serviceCode);return <div className="payment-row" key={b.id}><strong>{service?.name} · ₹{service?.priceInr}</strong>{p?<><span className={`readiness-pill ${p.state==='paid'?'ready':''}`}>{p.state==='paid'?'Payment verified':p.state.replaceAll('_',' ')}</span>{p.url&&p.state==='pending'&&<a className="button button-dark" href={p.url} target="_blank" rel="noreferrer"><UiText text={"Open Paytm test checkout "}/><ExternalLink size={15}/></a>}{p.state!=='paid'&&<button className="text-button" disabled={!!busy} onClick={()=>run(p.id,true)}><UiText text={"Verify payment status"}/></button>}{p.txnId&&<small><UiText text={"Transaction: "}/>{p.txnId}<br/><UiText text={"Fulfilment has not started."}/></small>}</>:<><label className="approval-checkbox"><input type="checkbox" checked={!!accepted[b.id]} onChange={e=>setAccepted({...accepted,[b.id]:e.target.checked})}/><span><UiText text={"The customer accepts this exact quoted visit fee."}/></span></label><button className="button button-dark" disabled={!accepted[b.id]||!!busy} onClick={()=>run(b.id)}><UiText text={"Create test payment request"}/></button></>}</div>})}</section>;
}
