import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,Cloud,Link2,X} from 'lucide-react';
import PixelTeammate from './PixelTeammate';
import type {WorkspaceState} from './api';
import {crewNames} from './crew-names';
export const readyTeams=[
  {code:'arjun',id:'baba',name:'Arjun · Counter team',tag:'Photo, voice or list → a reviewed bill',description:'Arjun interprets the shopping list. You review matched products and quantities; prices and stock come from your approved catalogue.',connection:'Billing works without Paytm API keys. Cash, credit and owner-confirmed UPI stay distinct.',example:'Review our saved bills and catalogue. Explain today’s recorded counter activity, stock needing attention and payment evidence. Do not invent missing sales or call an owner-confirmed payment provider verified.',options:[]},
  {code:'dukaan',id:'tara',name:'Tara · Online dukaan',tag:'A shareable shop. Orders captured.',description:'Tara turns your approved products into a simple customer storefront. Accepted pickup orders reserve recorded stock once.',connection:'Start with products and pickup instructions. Add your UPI QR or Paytm Checkout separately.',example:'Prepare a welcoming Hinglish shop introduction and explain our pickup process from approved facts. Flag missing hours and delivery details.',options:[]},
  {code:'naina',id:'ma',name:'Naina · Khata team',tag:'Know who owes what. Record repayments.',description:'Naina helps explain your credit ledger and prepare polite follow-up drafts. Every credit sale and repayment has an auditable entry.',connection:'Credit records work without a payment API. Received payments require your explicit confirmation.',example:'Review the saved credit ledger. Summarise outstanding balances by customer and prepare polite reminder drafts. Use only recorded balances and ask about missing due dates.',options:[]},
  {code:'kabir',id:'milo',name:'Kabir · Customer requests',tag:'Capture demand you would otherwise forget',description:'Kabir checks customer requests against this shop’s catalogue. You record what could not be fulfilled so it can inform your next decision.',connection:'Matches are limited to your products. No access to a Paytm merchant directory is claimed.',example:'Review recorded customer requests and our catalogue. Explain possible product matches and which requests still need my decision. Do not invent availability at another shop.',options:[]},
  {code:'ira',id:'riya',name:'Ira · Growth insights',tag:'Turn missed requests into useful signals',description:'Ira reads actual unmet requests and recommends practical actions for your review. No invented demand forecasts or sales guarantees.',connection:'Useful insights begin with your recorded requests and business facts.',example:'Analyse recorded unmet requests. Group repeated needs and suggest three practical next steps. State sample size and missing evidence. Do not promise sales or change prices.',options:[]},
  {code:'sia',id:'chotu',name:'Sia · Business advisor',tag:'Ask in your language. Get grounded help.',description:'Sia answers business questions using the team’s shared facts and workspace records. She explains what the data can and cannot show.',connection:'No external account is needed for advice grounded in your workspace.',example:'Explain my business’s recorded collections, outstanding credit and pending work in simple Hinglish. Separate owner-recorded cash and UPI from provider-verified online payments. Suggest what I should do next.',options:[]},
  {code:'saathi',id:'tara',name:'Aarav · Customer team',tag:'Turn enquiries into clear next steps',description:'Aarav prepares customer answers. Meera helps with sales replies and quotes; Naman keeps you informed.',connection:'Customer drafts work without app connections.',example:'A customer asks about our products, prices and delivery. Prepare a helpful Hinglish reply using our approved facts. Ask about any missing stock or delivery details instead of guessing.',options:[{key:'whatsapp',label:'Handle live WhatsApp enquiries',hint:'Pair WhatsApp and approve the reply rules.'},{key:'orders',label:'Create quotes and capture accepted orders',hint:'Add your approved products or services.'},{key:'payments',label:'Request and verify Paytm payments',hint:'Requires orders and your merchant MID + key.'},{key:'followups',label:'Follow up on unpaid accepted orders',hint:'Requires live WhatsApp, payments and approved timing.'}]},
  {code:'rang',id:'riya',name:'Riya · Marketing team',tag:'Content that sounds like your business',description:'Riya prepares captions and content plans. Enable the Instagram work you want her team to handle.',connection:'Content drafts work without Instagram or Paytm.',example:'Create three ready-to-use Hinglish Instagram captions and a simple three-day content plan for our business. Use only approved products, prices and facts. Do not invent discounts or claim anything was posted.',options:[{key:'publishing',label:'Publish approved Instagram posts',hint:'Connect a Business or Creator account.'},{key:'comments',label:'Reply to eligible comments',hint:'Verify the account’s comment permission.'},{key:'messages',label:'Handle eligible customer DMs',hint:'Verify the account’s messaging permission.'},{key:'orders',label:'Quote products and capture orders',hint:'Add your approved catalogue.'},{key:'bookings',label:'Book appointments',hint:'Connect and approve Google Calendar.'},{key:'payments',label:'Request and verify Paytm payments',hint:'Enable orders or bookings and connect merchant Paytm.'}]},
  {code:'udaan',id:'vijay',name:'Vijay · Website team',tag:'From business facts to a usable live link',description:'Vijay coordinates Aditi on assets, Dev on design, Kavya on copy and Nisha on factual checks.',connection:'No Paytm account needed. Review before publishing.',example:'Prepare the homepage structure, customer journey and clear calls to action for our business website from approved facts. Flag missing contact information; never invent reviews.',options:[]},
  {code:'sahaj',id:'milan',name:'Milan · Personal assistant',tag:'Remember commitments. Follow through.',description:'Milan prepares personal reminders and follow-up plans. Enable cloud sending when you are ready.',connection:'Reminder drafts work without WhatsApp or Paytm.',example:'Prepare a polite Hinglish reminder asking a customer to share their agreed payment details. Do not invent a balance, due date or prior commitment. Give me a short follow-up plan for review.',options:[{key:'whatsapp',label:'Send approved WhatsApp reminders',hint:'Pair WhatsApp; approve the person, message and time.'},{key:'bookings',label:'Coordinate appointments',hint:'Connect and approve Google Calendar.'}]},
  {code:'raabta',id:'milo',name:'Meera · Email team',tag:'Professional replies without the busywork',description:'Meera drafts useful sales replies. Connect Gmail to handle eligible inbound conversations.',connection:'Email drafts work without Gmail or Paytm.',example:'Draft a professional reply to a customer asking what we offer and how to order. Use approved facts, ask only essential questions and make the next step clear.',options:[{key:'inbox',label:'Handle the live Gmail inbox',hint:'Connect Gmail and enable eligible inbound replies.'},{key:'orders',label:'Create quotes and capture orders',hint:'Add your approved catalogue.'},{key:'bookings',label:'Book appointments',hint:'Connect and approve Google Calendar.'},{key:'payments',label:'Request and verify Paytm payments',hint:'Enable orders or bookings and connect merchant Paytm.'}]},
  {code:'nazar',id:'chotu',name:'Naman · Business insights',tag:'Know what happened. Know what needs you.',description:'Naman explains actual workspace records and suggests your next step. Empty records remain clearly visible.',connection:'No external account needed for workspace summaries.',example:'Summarise recorded orders, verified collections and work waiting for me. State clearly when data is missing. Give three useful next steps without inventing sales, profit or customer demand.',options:[{key:'stock',label:'Review recorded stock',hint:'Add your products and current inventory.'}]},
] as const;
export type ReadyTeamId=typeof readyTeams[number]['code'];
export function selectedReadyTeam(value:string|null|undefined):ReadyTeamId|undefined{return readyTeams.find(t=>t.code===value)?.code;}
const merchantCodes=['arjun','dukaan','naina','nazar','kabir','ira','sia','sahaj'];
export function ReadyTeamGallery({workspace,busy,onChoose}:{workspace:WorkspaceState;busy:boolean;onChoose:(id:ReadyTeamId)=>void}){
  const [category,setCategory]=useState('all'),[query,setQuery]=useState('');
  const visible=readyTeams.filter(t=>query.trim()?`${t.name} ${t.tag} ${t.description}`.toLowerCase().includes(query.trim().toLowerCase()):category==='all'||(category==='everyday'?merchantCodes.includes(t.code):!merchantCodes.includes(t.code)));
  const card=(team:typeof readyTeams[number])=>{const installed=workspace.blueprints.find(b=>b.presetId===team.code);return <button className={`office-job-card ${merchantCodes.includes(team.code)?'ready-core':'ready-extra'}`} key={team.code} disabled={busy} onClick={()=>onChoose(team.code)}><PixelTeammate id={team.id} name={team.name.split(' · ')[0]}/><div><span className="ready-crew-name">{crewNames[team.code]}</span><h3>{team.name}</h3><p>{team.tag}</p><small><i className={installed?.state==='active'?'is-active':''}/>{installed?.state==='active'?'Active · open teammate':installed?'Continue setup':'Meet this teammate'}</small></div><ArrowRight size={18}/></button>};
  return <section className="ready-team-gallery"><div className="office-section-heading"><div><span className="office-eyebrow">MEET YOUR AI TEAMMATES</span><h2>Find the right help for your work.</h2><p>Choose a familiar job. Your teammates share the same approved business brain.</p></div></div><div className="ready-gallery-controls"><div role="group" aria-label="Teammate categories">{[{id:'everyday',label:'Everyday work'},{id:'channels',label:'Customers & growth'},{id:'all',label:'All teammates'}].map(c=><button key={c.id} aria-pressed={category===c.id&&!query} onClick={()=>{setCategory(c.id);setQuery('')}}>{c.label}</button>)}</div><input type="search" aria-label="Find a teammate" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find billing, Instagram, reminders…"/></div><div className="office-job-grid">{visible.map(card)}</div>{!visible.length&&<div className="office-empty"><div><h3>No teammate matches this search.</h3><p>Try a name or a job, such as captions, bills or email.</p><button className="office-text" onClick={()=>{setQuery('');setCategory('all')}}>Show all teammates <ArrowRight size={15}/></button></div></div>}</section>;

}
export function ReadyTeamSetup({code,workspace,busy,onClose,onSave}:{code:ReadyTeamId;workspace:WorkspaceState;busy:boolean;onClose:()=>void;onSave:(code:ReadyTeamId,options:Record<string,boolean>,revision?:number)=>Promise<void>}){
  const team=readyTeams.find(t=>t.code===code)!,existing=workspace.blueprints.find(b=>b.presetId===code);
  const [options,setOptions]=useState<Record<string,boolean>>(()=>Object.fromEntries(team.options.map(o=>[o.key,existing?.presetOptions?.[o.key]??false])));
  const modal=useRef<HTMLElement>(null),close=useRef(onClose),working=useRef(busy);close.current=onClose;working.current=busy;
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow='hidden';modal.current?.querySelector<HTMLElement>('button')?.focus();
    const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!working.current)close.current();if(e.key==='Tab'){const items=Array.from(modal.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),a[href]')||[]),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};
    document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=overflow;previous?.focus()};},[]);
  const paymentInvalid=options.payments&&!options.orders&&!options.bookings,followupInvalid=options.followups&&(!options.payments||!options.whatsapp),valid=!paymentInvalid&&!followupInvalid;
  return <div className="office-modal-overlay"><section ref={modal} className="office-modal ready-team-setup" role="dialog" aria-modal="true" aria-labelledby="ready-team-title"><button className="office-close" aria-label="Close team setup" disabled={busy} onClick={onClose}><X size={20}/></button><PixelTeammate id={team.id}/><span className="office-eyebrow">YOUR TEAMMATE IS READY</span><h2 id="ready-team-title">{team.name}</h2><p>{team.description}</p><div className="ready-team-connection"><Cloud size={18}/><span>{team.connection}</span></div>{team.options.length>0&&<fieldset className="studio-fields" disabled={busy}><legend><Link2 size={16}/> Add live actions <small>Optional</small></legend>{team.options.map(o=><label className="office-check ready-team-option" key={o.key}><input type="checkbox" checked={!!options[o.key]} onChange={e=>setOptions({...options,[o.key]:e.target.checked})}/><span><strong>{o.label}</strong><small>{o.hint}</small></span></label>)}</fieldset>}{!valid&&<p role="alert" className="office-error">{paymentInvalid?'Enable orders or bookings before payment requests.':'Unpaid-order reminders need live WhatsApp and payment requests.'}</p>}<p className="office-footnote">Review the job next. Live actions wait for their required connections. Changing an active teammate’s settings pauses it for your approval.</p><button className="office-primary" disabled={busy||!valid} onClick={()=>void onSave(code,options,existing?.revision)}><Check size={16}/>{busy?'Saving teammate…':'Review my teammate'}</button></section></div>;
}
