import {useEffect,useRef,useState} from 'react';
import {Check,Download,FileText,LoaderCircle,RefreshCw,Sparkles,Upload} from 'lucide-react';
import {api,type RecordPreview,type RecordDocumentType,type WorkspaceState} from './api';
import {useLanguage} from './Language';
import type {ReadyTeamId} from './ReadyTeams';
import './record-documents.css';

const families:Record<RecordDocumentType,{title:string;lead:string;team:ReadyTeamId;description:string;columns:string[];example:string}>={
 payments:{title:'Payments report',lead:'Naman',team:'nazar',description:'Owner-reported sales and payments. Review received, pending and refunded entries.',columns:['record_id','date','description','amount_inr','payment_method','status'],example:'For RECORD-001 set description to Evening counter sale.'},
 credit:{title:'Udhaar / credit register',lead:'Naina',team:'naina',description:'One row per outstanding invoice. Keep customer, due date and follow-up notes together.',columns:['record_id','date','customer_name','contact','description','amount_inr','due_date','status','note'],example:'For DEMO-CREDIT-001 set note to Owner will review on Friday.'},
 orders:{title:'Customer order register',lead:'Tara',team:'dukaan',description:'Track customer requests, quantities, reported payment and fulfilment separately.',columns:['record_id','date','customer_name','contact','item','quantity','amount_inr','order_status','payment_status','note'],example:'For DEMO-ORDER-001 set note to Customer requested pickup at 5pm.'},
};
function downloadCsv(csv:string,fileName:string){const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=fileName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export default function RecordDocuments({token,workspace,onChange,onChoose,onOpenTask,initialType='payments'}:{token:string;workspace:WorkspaceState;onChange:()=>Promise<unknown>;onChoose:(id:ReadyTeamId)=>void;onOpenTask?:(id:string)=>void;initialType?:RecordDocumentType}){
 const {t}=useLanguage(),[type,setType]=useState<RecordDocumentType>(initialType),[selected,setSelected]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[upload,setUpload]=useState<{fileName:string;csv:string;preview:RecordPreview}|null>(null),[importApproved,setImportApproved]=useState(false),[practice,setPractice]=useState(false),[currentView,setCurrentView]=useState<RecordPreview|null>(null),[instruction,setInstruction]=useState(''),[writeApproved,setWriteApproved]=useState(false);
 const picker=useRef<HTMLInputElement>(null),locked=useRef(false),readRequest=useRef(0),readKey=useRef(crypto.randomUUID()),h=families[type],files=(workspace.recordImports||[]).filter(f=>(f.documentType||'payments')===type),doc=files.find(f=>f.id===selected)||files[0],proposal=doc?.writeProposal,active=workspace.blueprints.find(b=>b.presetId===h.team&&b.state==='active'),hold=!!workspace.controls?.paused||!!workspace.controls?.humanTakeover;
 useEffect(()=>{setType(initialType);setSelected('');setUpload(null);setCurrentView(null);setInstruction('');setWriteApproved(false);setError('');setNotice('');},[token,initialType]);
 useEffect(()=>{const request=++readRequest.current;setCurrentView(null);setWriteApproved(false);readKey.current=crypto.randomUUID();if(!doc)return;void api.exportRecord(token,doc.id).then(result=>api.previewRecords(token,result.csv)).then(result=>{if(request===readRequest.current)setCurrentView(result)}).catch(e=>{if(request===readRequest.current)setError((e as Error).message)});return()=>{readRequest.current++}},[token,doc?.id,doc?.hash]);
 async function act(label:string,fn:()=>Promise<void>){if(locked.current)return;locked.current=true;setBusy(label);setError('');setNotice('');try{await fn();await onChange()}catch(e){setError((e as Error).message)}finally{locked.current=false;setBusy('')}}
 function chooseType(next:RecordDocumentType){setType(next);setSelected('');setUpload(null);setImportApproved(false);setInstruction('');setWriteApproved(false);setError('');setNotice('')}
 async function readFile(file:File){setUpload(null);setImportApproved(false);if(file.size>60000){setError('Choose a CSV under 60 KB, with up to 200 rows.');return;}await act('Checking your file',async()=>{const csv=await file.text(),preview=await api.previewRecords(token,csv);setType(preview.documentType||'payments');setUpload({fileName:file.name,csv,preview});setPractice(preview.kind==='practice')})}
 async function readWithTeam(){if(!doc||!active)return;await act(`${h.lead} is starting a record review`,async()=>{await api.runTeammate(token,active.id,`Read ONLY importedRecordMemory file ${doc.id}, named ${doc.fileName}, current hash ${doc.hash}. It is ${doc.kind==='practice'?'fictional practice':'private owner-reported'} ${type} history. Explain the actual saved rows, their dates and coverage in my language. ${type==='credit'?'List outstanding invoice amounts only for pending rows; do not treat closed rows as debt, assume missing repayments, or combine this document with the operational credit ledger.':type==='orders'?'Separate enquiry/accepted/fulfilled/cancelled and pending/received/refunded; do not claim a stock reservation or a provider-verified payment.':'Explain received, pending and refunded totals in this payment report only.'} Give three useful next steps. Do not mix practice with business history, infer profit, send a reminder, edit a row or claim Paytm verification.`,readKey.current);setNotice(`${h.lead}’s review is saved as a cloud job. Its result appears in My AI team.`);onOpenTask?.(active.id)})}
 const shown=upload?.preview||currentView,columns=shown?.columns||h.columns;
 return <section className="office-card record-documents" aria-labelledby="record-documents-title">
  <header className="record-documents-head"><span className="record-document-icon"><FileText size={22}/></span><div><span className="office-eyebrow">{t('YOUR RECORDS · YOUR APPROVAL')}</span><h2 id="record-documents-title">{t('Give your teammate the right document')}</h2><p>{t('Download an exact template, upload your records, then read or review changes in the same saved file.')}</p></div></header>
  <div className="record-family-tabs" role="group" aria-label={t('Record template type')}>{(Object.keys(families) as RecordDocumentType[]).map(k=><button type="button" key={k} aria-pressed={type===k} disabled={!!busy} onClick={()=>chooseType(k)}>{t(families[k].title)}<small>{families[k].lead}</small></button>)}</div>
  {error&&<p className="office-error" role="alert">{error}</p>}{notice&&<p className="office-notice" role="status">{notice}</p>}{busy&&<p className="record-documents-progress" role="status"><LoaderCircle size={17} className="spin"/>{t(busy)}</p>}
  <p>{t(h.description)}</p><div className="record-document-downloads"><button type="button" className="office-secondary" disabled={!!busy} onClick={()=>void act('Preparing your template',async()=>{downloadCsv(await api.recordTemplate(type,false),`kaamset-${type}-template.csv`);setNotice('Blank template downloaded. Keep its column names in the same order.')})}><Download size={15}/>{t('Blank template')}</button><button type="button" className="office-secondary" disabled={!!busy} onClick={()=>void act('Preparing fictional example',async()=>{downloadCsv(await api.recordTemplate(type,true),`kaamset-${type}-fictional-sample.csv`);setNotice('Fictional example downloaded. Upload it to practice with your team.')})}><Download size={15}/>{t('Fictional example')}</button><button type="button" className="office-primary" disabled={!!busy} onClick={()=>picker.current?.click()}><Upload size={15}/>{t('Upload CSV')}</button><input ref={picker} type="file" hidden accept=".csv,text/csv" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void readFile(file)}}/></div>
  <details className="record-column-guide"><summary>{t('Exact columns and status values')}</summary><code>{h.columns.join(',')}</code><p>{t('Use YYYY-MM-DD dates, a unique record_id, and a positive rupee amount with up to two decimals. No passwords, OTPs or API keys.')}</p>{type==='payments'?<p>payment_method: <b>cash / upi / credit</b>. status: <b>received / pending / refunded</b>.</p>:type==='credit'?<p>amount_inr: {t('outstanding invoice amount while pending; original amount when closed')}. status: <b>pending / received</b>. {t('Use one row per invoice, not both a sale and its repayment. Partial repayments require the owner to provide the new outstanding amount.')}</p>:<p>quantity: <b>1–1000</b>. order_status: <b>enquiry / accepted / fulfilled / cancelled</b>. payment_status: <b>pending / received / refunded</b>.</p>}<small>{t('All three are private owner-reported documents. They do not update stock, the bill ledger or Paytm-verified payments.')}</small></details>
  {upload&&<div className="record-import-review"><h3>{t('Review before saving')} · {upload.fileName}</h3><p>{upload.preview.rows.length} {t('checked rows')} · {t(upload.preview.kind==='practice'?'fictional practice':'owner-reported history')}</p><label className="office-check"><input type="checkbox" checked={practice} disabled={!!busy||upload.preview.kind==='practice'} onChange={e=>{setPractice(e.target.checked);setImportApproved(false)}}/><span>{t('Keep this file as fictional practice data.')}</span></label><label className="office-check"><input type="checkbox" checked={importApproved} disabled={!!busy} onChange={e=>setImportApproved(e.target.checked)}/><span>{t('I checked these rows and approve saving them in private team memory.')}</span></label><button type="button" className="office-primary" disabled={!!busy||!importApproved} onClick={()=>void act('Saving checked document',async()=>{const saved=await api.saveRecords(token,{csv:upload.csv,fileName:upload.fileName,previewHash:upload.preview.hash,practice,approved:true});setSelected(saved.id);setUpload(null);setImportApproved(false);setNotice(saved.reused?'This exact file was already saved; no duplicate was added.':'Document saved. Your teammate can now read it and propose reviewed changes.')})}><Check size={15}/>{t('Save checked document')}</button><button type="button" className="office-text" disabled={!!busy} onClick={()=>setUpload(null)}>{t('Discard upload')}</button></div>}
  {!!files.length&&!upload&&<div className="record-saved-document"><label>{t('Saved document')}<select value={doc?.id||''} disabled={!!busy} onChange={e=>{setSelected(e.target.value);setInstruction('');setWriteApproved(false)}}>{files.map(f=><option key={f.id} value={f.id}>{f.fileName} · {f.rowCount} {t('rows')} · {t(f.kind==='practice'?'practice':'reported')}</option>)}</select></label><div className="office-actions"><button type="button" className="office-secondary" disabled={!!busy} onClick={()=>doc&&void act('Exporting current document',async()=>{const result=await api.exportRecord(token,doc.id);downloadCsv(result.csv,result.fileName);setNotice('The current saved version is downloaded, including approved updates.')})}><Download size={15}/>{t('Download current file')}</button>{active?<button type="button" className="office-primary" disabled={!!busy||hold||!workspace.briefApproved||workspace.limits.modelsRemaining<2} onClick={()=>void readWithTeam()}><Sparkles size={15}/>{t('Ask')} {h.lead} {t('to read it')}</button>:<button type="button" className="office-primary" disabled={!!busy} onClick={()=>onChoose(h.team)}>{t('Set up')} {h.lead}</button>}<button type="button" className="office-text" disabled={!!busy} onClick={()=>void act('Refreshing saved records',async()=>{await onChange()})}><RefreshCw size={14}/>{t('Refresh')}</button></div></div>}
  {shown&&<div className="record-document-table" tabIndex={0} role="region" aria-label={t('Saved document rows')}><table><caption>{t(upload?'Checked upload preview':'Current saved document')} · {Math.min(8,shown.rows.length)} / {shown.rows.length} {t('rows')}</caption><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{shown.rows.slice(0,8).map(r=>{const cells=r.cells||{record_id:r.id,date:r.date,description:r.description,amount_inr:(r.amountPaise/100).toFixed(2),payment_method:r.method,status:r.status};return <tr key={r.id}>{columns.map(c=><td key={c}>{cells[c]||'—'}</td>)}</tr>})}</tbody></table></div>}
  {doc&&!upload&&<div className="record-write-workflow"><h3>{t('Ask your teammate to update this document')}</h3><p>{t('State the record ID, field and exact new value. Your teammate prepares a change list; you approve it before anything is written.')}</p><label>{t('Your instruction')}<textarea rows={3} value={instruction} maxLength={1500} disabled={!!busy} placeholder={h.example} onChange={e=>{setInstruction(e.target.value);setWriteApproved(false)}}/></label>{doc.writeAttempt&&Date.now()-Date.parse(doc.writeAttempt.startedAt)<120000&&<p className="office-notice" role="status">{t('Your teammate is preparing a proposal. Refresh to check its result.')}</p>}<button type="button" className="office-secondary" disabled={!!busy||!active||hold||!workspace.briefApproved||instruction.trim().length<5||workspace.limits.modelsRemaining<1} onClick={()=>void act('Your teammate is preparing exact changes',async()=>{await api.proposeRecordUpdate(token,doc.id,{instruction:instruction.trim(),expectedHash:doc.hash});setWriteApproved(false);setNotice('A proposal is ready. Check every old and new value below before approving.')})}><Sparkles size={15}/>{t('Prepare update for review')}</button>
   {proposal&&<div className={`record-write-proposal ${proposal.state==='applied'?'is-applied':''}`}><h4>{t(proposal.state==='applied'?'Approved update saved':'Proposed changes · not saved yet')}</h4><p>{proposal.explanation}</p><dl>{proposal.changes.map(c=><div key={c.recordId+':'+c.field}><dt>{c.recordId} · {c.field}</dt><dd><span>{c.before||'—'}</span><strong>→ {c.after||'—'}</strong></dd></div>)}</dl>{proposal.state==='proposed'&&<><label className="office-check"><input type="checkbox" checked={writeApproved} disabled={!!busy||proposal.baseHash!==doc.hash} onChange={e=>setWriteApproved(e.target.checked)}/><span>{t('I approve these exact changes to this private reported document. This does not verify a payment or send a message.')}</span></label><button type="button" className="office-primary" disabled={!!busy||!writeApproved||hold||!active||proposal.baseHash!==doc.hash} onClick={()=>void act('Writing your approved document update',async()=>{await api.approveRecordUpdate(token,doc.id,{proposalId:proposal.id,proposalHash:proposal.hash,expectedHash:doc.hash,approved:true});setWriteApproved(false);setInstruction('');setNotice('Approved changes written once. Download the current file to use the updated document.')})}><Check size={15}/>{t('Approve and write these changes')}</button></>}</div>}
  </div>}
  <small className="record-document-policy">{t('Up to three private CSV files and 200 rows per file. Record versions prevent overwriting a newer edit. Reading and proposing use your workspace AI allowance. No payment or message is sent here.')}</small>
 </section>;
}
