import {useEffect,useRef,useState} from 'react';
import {Check,Copy,RefreshCw,ShoppingBag} from 'lucide-react';
import {api,type PublicReceipt,type PublicShop} from './api';
import {rupees} from './MerchantOps';
import './office.css';
export default function ShopFront({cap,receipt=false}:{cap:string;receipt?:boolean}){
 const [shop,setShop]=useState<PublicShop|null>(null),[bill,setBill]=useState<PublicReceipt|null>(null),[counts,setCounts]=useState<Record<string,number>>({}),[name,setName]=useState(''),[contact,setContact]=useState(''),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const requestKey=useRef(crypto.randomUUID()),flight=useRef(false);
 async function load(){if(receipt)setBill(await api.publicReceipt(cap));else setShop(await api.publicShop(cap))}
 useEffect(()=>{let cancelled=false;(receipt?api.publicReceipt(cap):api.publicShop(cap)).then(data=>{if(cancelled)return;if(receipt)setBill(data as PublicReceipt);else setShop(data as PublicShop)}).catch(e=>{if(!cancelled)setError((e as Error).message)});return()=>{cancelled=true}},[cap,receipt]);
 const total=shop?.products.reduce((sum,p)=>sum+p.unitPricePaise*(counts[p.id]||0),0)||0;
 async function checkout(){if(!shop||flight.current)return;flight.current=true;setBusy(true);setError('');try{const saved=await api.shopOrder(cap,{requestKey:requestKey.current,items:Object.entries(counts).filter(([,q])=>q>0).map(([offerId,quantity])=>({offerId,quantity})),customer:{name:name.trim(),contact:contact.trim()},accepted:true,expectedSnapshotHash:shop.snapshotHash});window.location.assign(saved.receiptUrl)}catch(e){setError((e as Error).message);try{setShop(await api.publicShop(cap));setAccepted(false)}catch{}}finally{flight.current=false;setBusy(false)}}
 const displayed=shop?.business||bill?.business;
 return <main className="shopfront"><header><a className="shopfront-brand" href="/">Kaam<span>Set</span></a><span>{receipt?'Order receipt':'Online dukaan'}</span></header><div className="shopfront-inner"><span className="office-eyebrow">{displayed?.city||'LOCAL BUSINESS'}</span><h1>{displayed?.name||'Opening your shop…'}</h1>{error&&<p className="office-error" role="alert">{error}</p>}{notice&&<p className="office-success" role="status">{notice}</p>}{!displayed&&error&&<button className="office-secondary" onClick={()=>void load().catch(e=>setError((e as Error).message))}>Retry <RefreshCw size={15}/></button>}
 {shop&&<><p className="shopfront-intro">{shop.pickupNote}</p><div className="shopfront-layout"><section className="shopfront-products">{shop.products.map(p=>{const available=p.availableQuantity!==null&&p.availableQuantity>=p.minimumQuantity;return <article key={p.id}><div className="shop-product-symbol"><ShoppingBag size={28}/></div><div><h2>{p.name}</h2><strong>{rupees(p.unitPricePaise)} / unit</strong><p>{p.terms}</p><small>{p.availableQuantity===null?'Ask the merchant to confirm stock':p.availableQuantity===0?'Currently unavailable':`${p.availableQuantity} units recorded · minimum ${p.minimumQuantity}`}</small></div><label>Quantity<input type="number" min={0} max={p.availableQuantity||0} step={1} disabled={busy||!available} value={counts[p.id]||0} onChange={e=>{setCounts({...counts,[p.id]:Number(e.target.value)});setAccepted(false);requestKey.current=crypto.randomUUID()}}/></label></article>})}</section><aside className="office-card shopfront-cart"><h2>Your pickup request</h2><div className="ops-total"><span>Total</span><strong>{rupees(total)}</strong></div><fieldset className="studio-fields" disabled={busy}><label>Your name<input value={name} maxLength={80} onChange={e=>{setName(e.target.value);setAccepted(false);requestKey.current=crypto.randomUUID()}}/></label><label>Contact for order updates<input value={contact} maxLength={100} onChange={e=>{setContact(e.target.value);setAccepted(false);requestKey.current=crypto.randomUUID()}}/></label><label className="office-check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I accept these products, quantities, prices and pickup instructions. Payment and pickup confirmation are separate.</span></label><button className="office-primary" disabled={!accepted||name.trim().length<2||total<=0||Object.values(counts).some(v=>!Number.isInteger(v)||v<0)} onClick={()=>void checkout()}>{busy?'Saving your order once…':'Place pickup request'} <Check size={16}/></button></fieldset><small>The merchant confirms fulfilment. An order request does not prove payment.</small></aside></div></>}
 {bill&&<section className="office-card customer-receipt"><span className="office-eyebrow">{bill.bill.number}</span><h2>{bill.bill.status==='awaiting_payment'?'Your order is saved.':'Your saved receipt.'}</h2><p>{new Date(bill.bill.createdAt).toLocaleString('en-IN')}</p>{bill.bill.items.map((item,i)=><div className="ops-record" key={i}><div><strong>{item.name}</strong><p>{item.quantity} × {rupees(item.unitPricePaise)}</p></div><strong>{rupees(item.amountPaise)}</strong></div>)}<div className="ops-total"><span>Order total</span><strong>{rupees(bill.bill.amountPaise)}</strong></div><p className="office-notice">{bill.bill.evidence}</p>{bill.bill.status==='awaiting_payment'&&bill.bill.upi&&<div className="receipt-payment"><h3>Pay through your UPI app</h3><p>{bill.bill.upi.accountType==='personal'?'Personal UPI payment handoff':'Merchant UPI instructions'} · recipient: <strong>{bill.bill.upi.payeeName}</strong></p>{bill.bill.upi.qr&&<img src={bill.bill.upi.qr} alt="Account owner’s original payment QR"/>}{bill.bill.upi.upiId&&<div className="receipt-upi-id"><code>{bill.bill.upi.upiId}</code><button className="office-secondary" onClick={()=>void navigator.clipboard.writeText(bill.bill.upi!.upiId!).then(()=>setNotice('UPI ID copied. Check the recipient name in your payment app.')).catch(()=>setError('Copy the UPI ID shown above.'))}><Copy size={16}/> Copy UPI ID</button></div>}<p>Pay {rupees(bill.bill.amountPaise)} and reference {bill.bill.number}. Check the recipient in your app. The merchant checks receipt in their own account; this page cannot automatically verify it.</p></div>}{bill.bill.paymentUrl&&bill.bill.status==='awaiting_payment'&&<a className="office-primary" href={bill.bill.paymentUrl}>Open Paytm Checkout</a>}<p>{bill.fulfilment}</p>{displayed?.contact&&<p>Contact the merchant: {displayed.contact}</p>}<button className="office-text" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><RefreshCw size={15}/> Refresh receipt status</button></section>}
 <footer>Powered by KaamSet · payment evidence and fulfilment are shown separately.</footer></div></main>;
}
