import type {ReadyTeamId} from './ReadyTeams';
type Starter={label:string;request:string};
export const teamStarters:Record<ReadyTeamId,Starter[]>={
  arjun:[{label:'What needs attention?',request:'Review our saved bills and recorded stock. Give me the most important counter issue, distinguish paid, credit, cancelled and pending bills, and suggest one next step. Do not describe all-time totals as today’s activity.'},{label:'Explain a bill',request:'Explain the latest non-cancelled saved bill in simple language, including items, amount, collection evidence and handover status. Do not claim an unverified payment was received.'}],
  dukaan:[{label:'Write my shop intro',request:'Write a short customer-ready Hinglish introduction for our online shop using approved products and pickup facts. Do not invent hours or delivery. Keep the owner note separate from public copy.'},{label:'Answer a pickup enquiry',request:'Draft a short customer reply explaining how to place a pickup order with us, using only approved facts. Ask one essential question if needed.'}],
  naina:[{label:'Who still owes me?',request:'Use our complete saved customer balances to explain who has outstanding udhaar. Recent ledger entries may be incomplete. Keep this brief and suggest one action; do not invent due dates.'},{label:'Draft a gentle reminder',request:'Prepare one polite Hinglish reminder for the customer with the largest recorded outstanding balance. Use the complete customer balance and no invented due date. Keep the copyable message separate from the owner note. This is a draft, not a sent message.'}],
  kabir:[{label:'Review unmet requests',request:'Review the saved unmet customer requests. Explain possible matches within our approved catalogue, what remains uncertain and the smallest decision I should make. Do not promise another merchant’s stock.'},{label:'What can we offer?',request:'Review the most recent customer request against our catalogue and recorded availability. Prepare a short proposed reply, clearly marking anything needing my confirmation.'}],
  ira:[{label:'Find a useful pattern',request:'Use actual saved customer requests to identify repeated unmet needs. State the number of records supporting each pattern. Suggest up to three small experiments and how I could check their results; do not invent forecasts.'},{label:'What should I try next?',request:'From approved business facts and actual unmet requests, recommend one practical next experiment. Explain the evidence and what I should measure before spending more.'}],
  sia:[{label:'What should I do next?',request:'Briefly explain what needs my attention across the actual saved bills, udhaar and customer requests. Separate owner-recorded cash/UPI from provider-verified payments. Prioritise one useful next action. Do not call all-time figures today’s sales.'},{label:'Explain my money',request:'Explain recorded collections, outstanding credit and expenses in simple Hinglish. Distinguish manual receipts from provider-verified online payments. Do not call collections profit. Use full summary totals.'}],
  nazar:[{label:'Give me a quick briefing',request:'Give me a short briefing: completed work, pending evidence and one priority needing me, from actual saved records. Exclude cancelled orders from payment reminders. State record coverage.'},{label:'Check pending work',request:'Explain the saved orders and commitments still needing owner attention. Tell me one thing I can resolve next. Do not invent deadlines or completed actions.'}],
  sahaj:[{label:'Draft a personal reminder',request:'Draft a polite Hinglish message asking a customer to share their agreed payment details. Do not invent any balance or deadline. Ask one essential question about the recipient or schedule if needed. Keep the message separate from my scheduling note.'},{label:'Plan my follow-ups',request:'Review saved reminders and commitments. Prepare a short follow-up plan with one priority; distinguish a proposed schedule from a message actually sent. Ask about missing recipient/time instead of guessing.'}],
  saathi:[{label:'Reply to an enquiry',request:'A customer asks what we sell and how to order. Draft a concise helpful Hinglish reply using approved facts and prices. Ask at most one essential question. Keep owner-only notes separate.'},{label:'Handle a discount request',request:'Draft a useful customer reply asking for a discount. Follow our saved commercial rules, do not offer an unapproved discount, and give a clear next step without losing the customer’s interest.'}],
  rang:[{label:'Write three captions',request:'Create three short customer-ready Hinglish Instagram captions using our approved products and facts. Give each a clear call to action. Do not invent an offer, price, testimonial or posting result.'},{label:'Plan three days of posts',request:'Create a practical three-day Instagram plan from approved business facts. Include the post idea, concise caption and a photo we would need to provide. No invented offers or claim that anything was published.'}],
  udaan:[{label:'Plan my homepage',request:'Prepare a concise mobile homepage structure and ready-to-use copy from approved business facts. Include one clear customer action and flag missing public contact details. Do not invent reviews or a live URL.'},{label:'Improve the customer journey',request:'Propose a simple website customer journey from first visit to enquiry or order using our approved business facts. Give useful section copy and calls to action, without exposing private customer or payment records.'}],
  raabta:[{label:'Draft a sales reply',request:'Draft a professional customer email asking what we offer and how to order. Include a subject and short ready-to-send body from approved facts, with one clear next step. Keep owner notes separate.'},{label:'Follow up politely',request:'Prepare a short professional email following up on a customer enquiry. Do not invent a previous quote, agreed amount, deadline or attachment. Ask one essential question if needed.'}],
};
