import {useState} from 'react';
import {ArrowRight,Copy,ExternalLink,Globe,ShieldCheck} from 'lucide-react';
import {api,type WorkspaceState} from './api';
import PixelTeammate from './PixelTeammate';
export default function WebsiteStudio({token,workspace,onChange,onBuild}:{token:string|null;workspace:WorkspaceState|null;onChange:()=>Promise<unknown>;onBuild:()=>void}){
  const [name,setName]=useState(''),[instructions,setInstructions]=useState('Create a polished, mobile-friendly business website in Hinglish. Explain our offer clearly and make it easy to enquire. Keep every business claim grounded.'),[phone,setPhone]=useState(''),[approved,setApproved]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState('');
  const vijay=workspace?.blueprints.find(b=>b.state==='active'&&b.plan.skills.includes('website_publish'));
  const cloudWorking=workspace?.sites?.some(site=>['queued','working'].includes(site.state));
  async function run(fn:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');try{await fn();await onChange()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <section className="merchant-tool website-studio"><div className="milan-heading"><PixelTeammate id="vijay" state={busy||cloudWorking?'working':'idle'}/><div><span className="card-kicker">VIJAY · GEMINI 3.1 PRO · HIGH THINKING</span><h2>Your business deserves a home online.</h2><p>Describe your style. Vijay builds a responsive site from approved facts and publishes it with a usable KaamSet link.</p></div></div>{error&&<p className="workspace-error" role="alert">{error}</p>}
    {!vijay&&<div className="setup-box"><strong>Build and activate Vijay first.</strong><p>Your approved playbook becomes his source. He checks the job before building.</p><button className="button button-dark" onClick={onBuild}>Give Vijay a website job <ArrowRight size={16}/></button></div>}
    <div className="merchant-form-grid"><label>Public business name<input maxLength={80} value={name} placeholder="Your business name" onChange={e=>{setName(e.target.value);setApproved(false)}}/></label><label>Public WhatsApp number (optional)<input value={phone} inputMode="tel" placeholder="91 followed by your 10-digit number" maxLength={12} onChange={e=>{setPhone(e.target.value.replace(/\D/g,''));setApproved(false)}}/></label></div><label>What should the website feel like?<textarea rows={4} maxLength={1200} value={instructions} onChange={e=>{setInstructions(e.target.value);setApproved(false)}}/></label>
    <div className="website-scope"><Globe size={20}/><div><strong>A real, shareable business site</strong><p>Mobile layout, product or service cards, useful FAQs and a contact link. Model-selected storefront, studio or service layout and colour palette.</p></div></div><label className="approval-checkbox"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/> I approve publishing these business facts and the contact number publicly. My playbook contains no passwords or private customer information.</label>
    <button className="button button-primary" disabled={busy||!token||!vijay||!approved||name.trim().length<2||instructions.trim().length<5||!!phone&&!/^91[6-9]\d{9}$/.test(phone)} onClick={()=>run(async()=>{await api.buildSite(token!,{blueprintId:vijay!.id,businessName:name,instructions,...(phone?{phone}:{}),publishApproved:true});setApproved(false)})}>Build & publish with Vijay <Globe size={17}/></button><p className="small-muted">Pro with high thinking may take longer. The cloud worker continues if you close the browser. Trial sites expire with this 24-hour guest workspace.</p>
    <div className="order-list">{workspace?.sites?.slice().reverse().map(site=><article key={site.id}><div className="task-result-head"><strong>{site.businessName}</strong><span className="readiness-pill">{site.state.replaceAll('_',' ')}</span></div>{site.reason&&<p>{site.reason}</p>}{site.state==='published'?<><a href={site.url} target="_blank" rel="noreferrer">Open live website <ExternalLink size={14}/></a><button className="text-button" onClick={()=>run(async()=>{await navigator.clipboard.writeText(site.url);setCopied(site.id)})}><Copy size={14}/>{copied===site.id?'Copied':'Copy website link'}</button><p className="site-url">{site.url}</p><button className="text-button" disabled={busy||!token} onClick={()=>run(()=>api.unpublishSite(token!,site.id))}>Unpublish website</button></>:['queued','working'].includes(site.state)?<p role="status">Vijay is designing and writing in the cloud. Your link appears after the site is published.</p>:null}</article>)}</div><div className="quote-safety"><ShieldCheck size={18}/><p>Website text is rendered safely, with no generated scripts. Prices come from approved offers. Your public site contains no workspace credentials or customer records.</p></div>
  </section>;
}
